/** THE ENGLISH COPY — temporary. The website is English-only (docs/DESIGN-SYSTEM-V5.md §9): there is no interface
 *  language, no locale and no translation. This module is what is left of the v4 dictionaries: one flat map of the
 *  English strings that pages written before the redesign still look up by key, so they keep compiling until their
 *  page package rewrites them.
 *
 *  Rules (EN-1, 2026-10-03):
 *  - Add no keys. New and rewritten code writes its English inline, in the component.
 *  - A page package deletes the keys of the code it rewrites (and every key that becomes unused):
 *    tests/unit/english-copy.test.ts fails on a key nothing uses and on a key used in the source that is missing here.
 *  - The consolidation package deletes this file once no file imports it.
 *
 *  `T('btn.save')`; `` T.dyn(`stage.${x}`) `` for a key built at runtime (unknown keys become readable words);
 *  `T.f(key, { name })` fills `{name}`; `T.p(key, n)` picks `one|other` by the count and fills `{n}`. */
const COPY = {
  // ---- common --------------------------------------------------------------------------------------------------------
  // stages
  'stage.STORY': 'Story',
  'stage.CAST_AND_WORLD': 'Cast & World',
  'stage.STORYBOARD': 'Storyboard',
  'stage.PRODUCE': 'Produce',
  'stage.FINAL_CUT': 'Final Cut',
  'stage.COMPLETE': 'Complete',

  // kinds
  'kind.EPISODE': 'Episode',
  'kind.SHORT': 'Short',
  'kind.MUSIC_VIDEO': 'Music video',
  'kind.SHOW': 'Show',
  'kind.SEASON': 'Season',

  // styles
  'style.CARTOON': 'Cartoon',
  'style.ANIME': 'Anime',
  'style.REALISTIC': 'Realistic',
  'style.CARTOON.hint': 'Bold shapes, flat colour, exaggerated motion.',
  'style.ANIME.hint': 'Clean line, expressive eyes, painted light.',
  'style.REALISTIC.hint': 'Natural proportions, photographic light.',

  // workspace tabs
  'tab.overview': 'Overview',
  'tab.story': 'Story',
  'tab.storyboard': 'Storyboard',
  'tab.produce': 'Produce',
  'tab.finalCut': 'Final Cut',
  'tab.voice': 'Voice',

  // buttons
  'btn.create': 'Create',
  'btn.save': 'Save',
  'btn.saved': 'Saved',
  'btn.cancel': 'Cancel',
  'btn.discard': 'Discard changes',
  'btn.delete': 'Delete',
  'btn.duplicate': 'Duplicate',
  'btn.edit': 'Edit',
  'btn.done': 'Done',
  'btn.back': 'Back',
  'btn.next': 'Next',
  'btn.upload': 'Upload',
  'btn.add': 'Add',
  'btn.remove': 'Remove',
  'btn.close': 'Close',
  'btn.open': 'Open',
  'btn.view': 'View',
  'btn.addShot': 'Add Shot',
  'btn.addScene': 'Add Scene',
  'btn.addBeat': 'Add beat',
  'btn.addLine': 'Add line',
  'btn.moveUp': 'Move up',
  'btn.moveDown': 'Move down',
  'btn.select': 'Select',
  'btn.selected': 'Selected',
  'btn.createNew': 'Create new',
  'btn.markDone': 'Mark this step done',

  // labels
  'label.title': 'Title',
  'label.titleAr': 'Arabic title',
  'label.logline': 'Logline',
  'label.synopsis': 'Synopsis',
  'label.genre': 'Genre',
  'label.style': 'Visual style',
  'label.language': 'Language',
  'label.dialect': 'Dialect',
  'label.aspect': 'Aspect',
  'label.duration': 'Duration',
  'label.seconds': 'seconds',
  'label.cast': 'Cast',
  'label.locations': 'Locations',
  'label.notes': 'Notes',
  'label.name': 'Name',
  'label.nameAr': 'Arabic name',
  'label.role': 'Role',
  'label.search': 'Search',
  'label.status': 'Status',
  'label.scenes': 'Scenes',
  'label.shots': 'Shots',
  'label.takes': 'Takes',
  'label.frames': 'Frames',
  'label.runtime': 'Runtime',
  'label.target': 'Target',
  'label.updated': 'Updated',
  'label.created': 'Created',
  'label.arc': 'Season arc',
  'label.confirmTitle': 'Type the title to confirm',
  'label.english': 'English',
  'label.arabic': 'Arabic',
  'label.all': 'All',
  'label.sample': 'Sample',
  'label.sampleContent': 'Sample content',
  'label.timeOfDay': 'Time of day',
  'label.location': 'Location',
  'label.scene': 'Scene',
  'label.shot': 'Shot',
  'label.framing': 'Framing',
  'label.camera': 'Camera',
  'label.transition': 'Begins with',
  'label.dialogue': 'Dialogue',
  'label.purpose': 'Purpose',
  'label.action': 'Action',
  'label.people': 'People in the shot',
  'label.songWindow': 'Song window',
  'label.kind': 'Kind',
  'label.description': 'Description',
  'label.landmarks': 'Landmarks',
  'label.lighting': 'Lighting states',
  'label.interior': 'Interior',
  'label.exterior': 'Exterior',
  'label.sex': 'Sex',
  'label.age': 'Age',
  'label.build': 'Build',
  'label.face': 'Face',
  'label.hair': 'Hair',
  'label.skin': 'Skin',
  'label.eyes': 'Eyes',
  'label.distinguishing': 'Distinguishing marks',
  'label.wardrobe': 'Wardrobe',
  'label.personality': 'Personality',
  'label.species': 'Species',
  'label.pitch': 'Pitch',
  'label.pace': 'Pace',
  'label.timbre': 'Timbre',
  'label.voiceNotes': 'Performance notes',
  'label.masterPlate': 'Master plate',
  'label.female': 'Female',
  'label.male': 'Male',

  // libraries
  'lib.addShort': 'Add Short',
  'lib.addMusicVideo': 'Add Music Video',
  'lib.addCharacter': 'Add Character',
  'lib.addLocation': 'Add Location',
  'lib.voiceSelected': 'voice chosen',
  'lib.noVoice': 'no voice yet',
  'lib.search': 'Search…',
  'lib.noMatches': 'Nothing matches your search.',
  'lib.clearSearch': 'Clear search',
  'lib.sortRecent': 'Recently updated',
  'lib.sortTitle': 'Title',
  'lib.filterStyle': 'Style',
  'lib.filterStage': 'Stage',
  'lib.inheritedFromShow': 'from the show',
  'lib.images': 'Pictures',
  'lib.videos': 'Clips',
  'lib.audio': 'Sound',
  'lib.uploadHint': 'Files you add are checked, stored in the studio library on the server and listed here with their origin.',
  'media.unavailable': 'File not available',
  'media.unavailable.hint': 'The record exists but its file is missing from the studio library: it was removed from the library folder, or the volume was replaced.',
  'media.stored': 'Uploaded',
  'media.generated': 'Generated',
  'media.added': 'File added.',
  'toast.emptied': 'The studio is empty.',

  // empty states
  'empty.shows.hint': 'A show holds seasons and episodes that share a cast and a world.',
  'empty.shorts': 'No shorts yet.',
  'empty.shorts.hint': 'A short is one film, from idea to final cut.',
  'empty.musicVideos': 'No music videos yet.',
  'empty.musicVideos.hint': 'A music video starts with its song.',
  'empty.characters': 'No characters yet.',
  'empty.locations': 'No locations yet.',
  'empty.assets': 'The library is empty.',
  'empty.shots': 'No shots yet.',
  'empty.shots.hint': 'Add a scene, then plan its shots.',
  'empty.scenes': 'No scenes yet.',
  'empty.takes': 'No takes yet.',
  'empty.dialogue': 'No dialogue in this shot.',
  'empty.cast': 'Nobody in the cast yet.',
  'empty.locationsIn': 'No locations chosen yet.',
  'empty.references': 'No reference views yet.',

  // misc
  'toast.saved': 'Saved.',
  'toast.created': 'Created.',
  'toast.deleted': 'Deleted.',
  'toast.takeSelected': 'Take selected.',
  'misc.notFound': 'Not here',
  'misc.notFound.hint': 'This page does not exist, or the item was deleted.',
  'misc.of': 'of',

  // section tabs
  'tab.seasons': 'Seasons',
  'tab.characters': 'Characters',
  'tab.locations': 'Locations',
  'tab.settings': 'Settings',
  'tab.song': 'Song & Lyrics',
  'tab.performers': 'Performers',
  'tab.visual': 'Visual Story',
  'tab.usedIn': 'Used In',
  'tab.views': 'Views',
  'tab.lighting': 'Lighting & Variations',
  'tab.props': 'Props',
  'meta.episodes': 'episodes',
  'meta.artist': 'Artist',
  'meta.noArtist': 'No performer yet',
  // home
  // misc
  'misc.player': 'Player',
  'misc.seek': 'Seek',
  'misc.play': 'Play',
  'misc.pause': 'Pause',
  'misc.noArtwork': 'No artwork yet',
  'misc.details': 'Details',
  'meta.views': 'views',
  'lib.searchCharacters': 'Search by name or role',
  'btn.addSection': 'Add section',
  'lib.sort': 'Sort',
  'lib.filterProduction': 'Production',
  'lib.filterUsage': 'Usage',
  'misc.episodeOf': 'Episode',

  // jobs and generation (the real backend)
  'btn.refresh': 'Refresh',
  'status.title': 'Engines',
  'status.lead': 'What this studio can do right now, and where each engine runs.',
  'status.video': 'Video (MiniMax)', // v4-lint: allow engine — pre-existing copy that names an engine; the page package that rewrites this page writes it engine-free (Settings)
  'status.story': 'Story engine',
  'status.images': 'Images (ComfyUI)', // v4-lint: allow engine — pre-existing copy that names an engine; the page package that rewrites this page writes it engine-free (Settings)
  'status.voice': 'Voices',
  'status.transcription': 'Transcription',
  'status.music': 'Music',
  'status.ready': 'Ready',
  'status.notReady': 'Not ready',
  'status.hosted': 'Hosted',
  'status.local': 'Local GPU',
  'status.offline': 'Offline',
  'status.connected': 'Connected to the studio server',
  'status.disconnected': 'Reconnecting to the studio server…',
  // ---- end of design v3 block ----
  'tab.episodes': 'Episodes',
  'tab.showCast': 'Cast',
  'lib.filterLanguage': 'Language',
  'lib.sortName': 'Name',
  'lib.sortMostUsed': 'Most used',
  // ---- kit -----------------------------------------------------------------------------------------------------------
  // library views and metadata
  'view.grid': 'Grid',
  'view.list': 'List',
  // ---- design v3: kit, Studio Company, department and agent pages (docs/DESIGN-SYSTEM-V3.md §6, §9.1–9.3) ----
  'v3.noPictureYet': 'No picture yet',
  'v3.breadcrumb': 'Breadcrumb',
  'v3.retry.withChange': 'Retry with a change',
  'v3.retry.what': 'What did you change?',
  'v3.retry.placeholder': 'e.g. replaced the reference picture',
  'v3.retry.hint': 'Unchanged, this failure would repeat. What you write is recorded with the retry.',

  // job progress: the worker's real phases, in words
  'jp.QUEUED': 'Queued',
  'jp.PREPARING': 'Preparing',
  'jp.GENERATING': 'Generating',
  'jp.VALIDATING': 'Checking the result',
  'jp.POSTPROCESSING': 'Saving',
  'jp.phases': 'Phases',
  'jp.elapsed': 'Elapsed',
  'jp.step': 'step',
  'jp.done': 'done',
  'jp.failed': 'failed',
  'jp.skipped': 'skipped',
  // the phases character and voice jobs report (progress.phase), read as `jp.${phase}` (finding 14)
  'jp.preparing': 'Preparing',
  'jp.recovering': 'Recovering',
  'jp.design': 'Designing',
  'jp.designing': 'Designing',
  'jp.appearance': 'Drawing the portrait',
  'jp.voice': 'Building the voice',
  'jp.drawing': 'Drawing',
  'jp.cloning': 'Cloning the voice',
  'jp.speaking': 'Speaking',
  'jp.recording': 'Recording',
  'jp.retry scheduled': 'Retry scheduled',
  'jp.awaiting review': 'Awaiting review',
  'jp.cancelled': 'Cancelled',
  // error codes → plain copy and the one recovery action
  'err.unknown': 'The step failed.',
  'err.openJob': 'Open the job',
  'err.UNAVAILABLE': 'The engine is not reachable.',
  'err.UNAVAILABLE.hint': 'The studio could not reach the service that does this step.',
  'err.UNAVAILABLE.fix': 'Start the engine, then retry',
  'err.NOT_CONFIGURED': 'The model is not set up.',
  'err.NOT_CONFIGURED.hint': 'A model or a key this step needs is missing.',
  'err.NOT_CONFIGURED.fix': 'Download the model (Settings → Engines)',
  'err.PROVIDER': 'The engine returned nothing usable.',
  'err.PROVIDER.hint': 'It ran, but what came back did not pass the checks.',
  'err.PROVIDER.fix': 'Try again',
  'err.INVALID': 'Something in the request is not valid.',
  'err.INVALID.hint': 'Check the fields the message names.',
  'err.INVALID.fix': 'Check the fields',
  'err.CONSENT_REQUIRED': 'A consent choice is needed for this recording.',
  'err.CONSENT_REQUIRED.hint': 'Say whether it is your own voice or you have the speaker’s permission; a voice is only made from a recording with consent.',
  'err.CONSENT_REQUIRED.fix': 'Choose consent',
  'err.ASSET_PROTECTED': 'This file is kept for continuity.',
  'err.ASSET_PROTECTED.hint': 'A character who has been in a video rests on it, so it cannot be removed.',
  'err.MISSING_REFERENCE': 'No usable reference.',
  'err.MISSING_REFERENCE.hint': 'This step needs a reference you add yourself: a picture for the look, a recording for the voice.',
  'err.MISSING_REFERENCE.fix': 'Add a reference',
  'err.LOCKED': 'Preserved for continuity.',
  'err.LOCKED.hint': 'This character has been in a video; the look and voice they appeared with are kept.',
  'err.LOCKED.fix': 'See where it was used',
  'err.CONFLICT': 'Already running.',
  'err.CONFLICT.hint': 'The same step is running for this item.',
  'err.CONFLICT.fix': 'Open the job',
  'err.NOT_FOUND': 'The record is gone.',
  'err.NOT_FOUND.hint': 'What this step needed was deleted in the meantime.',
  'err.NOT_FOUND.fix': 'Go back',
  'err.CANCELLED': 'Cancelled.',
  'err.CANCELLED.hint': 'You stopped it; what was finished is kept.',
  // image preview
  'preview.empty': 'No picture yet',

  // ---- design v4 (F2): the interface kit (docs/DESIGN-SYSTEM-V4.md §5.2, §5.10–5.11, §5.15–5.19) ------------------
  'kit.optional': 'optional',
  'kit.dismiss': 'Dismiss',
  'kit.undo': 'Undo',
  'kit.change': 'Change',
  'kit.loading': 'Loading…',
  'kit.deleteAll': 'This removes it and everything that belongs to it.',
  'kit.err.unknownHint': 'The studio could not finish this step. What was finished before it is kept.',
  // status (§5.10)
  'kit.state.running': 'Running',
  'kit.sub.waiting': 'Waiting for you',
  'kit.sub.refused': 'Refused by the quality check',
  'kit.identity.draft': 'Draft — awaiting your approval',
  'kit.identity.approved': 'Approved',
  'kit.identity.locked': 'Locked',
  'kit.identity.lockedIn': 'Locked · in {n} video|Locked · in {n} videos',
  'kit.identity.none': 'No image yet',
  'kit.stage.STORY': 'Story',
  'kit.stage.CAST_AND_WORLD': 'Cast & world',
  'kit.stage.STORYBOARD': 'Storyboard',
  'kit.stage.PRODUCE': 'Producing',
  'kit.stage.FINAL_CUT': 'Final cut',
  'kit.stage.COMPLETE': 'Finished',
  'kit.filter': 'Filter',
  'kit.filter.title': 'Filters',
  'kit.filter.active': 'Active filters',
  'kit.filter.remove': 'Remove the filter {label}',
  'kit.filter.clearAll': 'Clear all',
  'kit.view': 'View',
  // in-page navigation (§5.11)
  'kit.onThisPage': 'On this page',
  'kit.crumbs.more': 'The rest of the path',
  // overlays (§5.17)
  // forms (§5.18)
  'kit.errors.title': 'Check these fields before you continue',
  'kit.chip.remove': 'Remove {label}',
  'kit.drop.browse': 'Browse',
  'kit.drop.replace': 'Replace',
  'kit.save.saved': 'Saved',
  'kit.save.saving': 'Saving…',
  'kit.save.unsaved': 'Not saved — retrying',
  'kit.rec.consent': 'Whose voice is this?',
  'kit.rec.mine': 'This is my voice',
  'kit.rec.permission': 'I have the speaker’s permission',
  'kit.rec.needConsent': 'Choose one of the two statements before you record.',
  'kit.rec.record': 'Record',
  'kit.rec.stop': 'Stop',
  'kit.rec.again': 'Record again',
  'kit.rec.level': 'Input level',
  'kit.rec.recording': 'Recording',
  'kit.rec.recorded': 'Your recording, {time}',
  'kit.rec.denied': 'The microphone is not available. Allow it for this site in the browser, then try again.',
  'kit.rec.unsupported': 'This browser cannot record sound. Upload a recording instead.',
  // approval card (§5.15)
  'kit.approval.approve': 'Approve',
  'kit.approval.requestChanges': 'Request changes',
  'kit.approval.whatChange': 'What should change?',
  'kit.approval.sendBack': 'Send back',
  'kit.approval.approved': 'Approved',
  'kit.approval.sent': 'Sent back with your note',
  'kit.approval.failed': 'The decision was not saved.',
  'kit.approval.failedWhy': 'Nothing changed. Try again in a moment.',
  // creation flows (§5.19)
  'kit.create.how': 'How do you want to start?',
  'kit.create.auto': 'Let the studio propose',
  'kit.create.autoHint': 'A line is enough. You review everything before anything is made.',
  'kit.create.manual': 'Write it yourself',
  'kit.create.manualHint': 'A title or a line; every other field has a sensible default.',
  'kit.create.moreControl': 'More control',
  'kit.create.preview': 'Preview',
  'kit.create.another': 'Another idea',
  'kit.create.changePrefs': 'Change preferences',
  'kit.create.steps': 'Steps',
  'kit.create.stepOf': 'Step {n} of {total}',

  // ---- /kit, the specimen page (development only) ---------------------------------------------------------------
  'kit.page.title': 'Interface kit',
  'kit.spec.eyebrow': 'Development only · not in production builds',
  'kit.spec.lead': 'Every part of the interface kit in every state: at rest, hovered, focused, disabled, loading, failed and selected.',
  'kit.spec.start': 'Start with the buttons',
  'kit.spec.sec.preferences': 'Contrast and density',
  'kit.spec.sec.buttons': 'Buttons',
  'kit.spec.sec.status': 'Status',
  'kit.spec.sec.navigation': 'In-page navigation',
  'kit.spec.sec.forms': 'Forms',
  'kit.spec.sec.choices': 'Choices',
  'kit.spec.sec.overlays': 'Overlays',
  'kit.spec.sec.states': 'Empty, loading, error and partial',
  'kit.spec.sec.approval': 'Approval card',
  'kit.spec.sec.headers': 'Headers',
  'kit.spec.sec.creation': 'Creation flow',
  'kit.spec.preferences.lead': 'More contrast raises muted and faint text and every boundary one step. Compact density is the cutting room’s default.',
  'kit.spec.contrast': 'Contrast',
  'kit.spec.contrast.system': 'As the system',
  'kit.spec.contrast.standard': 'Standard',
  'kit.spec.contrast.more': 'More',
  'kit.spec.contrast.osOn': 'This browser asks for more contrast.',
  'kit.spec.contrast.osOff': 'This browser does not ask for more contrast.',
  'kit.spec.contrast.now': 'In effect: {value}.',
  'kit.spec.contrast.fg': 'Titles and the work: ivory.',
  'kit.spec.contrast.muted': 'Muted text: leads and secondary lines.',
  'kit.spec.contrast.faint': 'Faint text: hints and timestamps.',
  'kit.spec.density': 'Density',
  'kit.spec.density.comfortable': 'Comfortable',
  'kit.spec.density.compact': 'Compact',
  'kit.spec.density.hint': 'Compact: 32 px controls and 13/20 text (Arabic 14/22). On touch, controls stay 44 px.',
  'kit.spec.density.body': 'The same words, the same controls, a tighter rhythm.',
  'kit.spec.rest': 'Rest',
  'kit.spec.hover': 'Hover',
  'kit.spec.focus': 'Focus',
  'kit.spec.disabled': 'Disabled',
  'kit.spec.loading': 'Loading',
  'kit.spec.error': 'Error',
  'kit.spec.selected': 'Selected',
  'kit.spec.optional': 'Optional',
  'kit.spec.pressed': 'Pressed',
  'kit.spec.iconOnly': 'Icon only',
  'kit.spec.sizes': 'Sizes',
  'kit.spec.states': 'States',
  'kit.spec.count': 'Count',
  'kit.spec.phase': 'With a phase',
  'kit.spec.try': 'Try them',
  'kit.spec.static': 'Drawn open',
  'kit.spec.static.menu': 'A menu: an item with a description, hovered, focused, disabled, and the one that removes.',
  'kit.spec.static.toast': 'A toast with Undo stays at least 10 seconds, longer while hovered or focused.',
  'kit.spec.static.dialog': 'A confirm: the title names the object; the one filled red button deletes.',
  'kit.spec.v.primary': 'Primary',
  'kit.spec.v.secondary': 'Secondary',
  'kit.spec.v.quiet': 'Quiet',
  'kit.spec.v.danger': 'Danger',
  'kit.spec.v.destructive': 'Destructive (dialogs only)',
  'kit.spec.buttons.lead': 'One ivory primary per region. The filled red button lives only inside a confirm.',
  'kit.spec.status.lead': 'State lives under the picture, in words: a dot and a phrase, never colour alone.',
  'kit.spec.tone.idle': 'Not started',
  'kit.spec.tone.done': 'Done',
  'kit.spec.tone.failed': 'Failed',
  'kit.spec.drawingShot': 'drawing shot 7 of 20',
  'kit.spec.strip': 'Waiting for you: approve the story of Episode 4',
  'kit.spec.progress': 'Progress of the export',
  'kit.spec.navigation.lead': 'Switching is instant: only the 2 px underline moves. The arrow keys follow the reading direction.',
  'kit.spec.tabsLabel': 'Episode workspace',
  'kit.spec.panel': 'The {name} panel. No fade: it is simply there.',
  'kit.spec.show': 'The Last Sip',
  'kit.spec.season': 'Season 1',
  'kit.spec.episode': 'Episode 3',
  'kit.spec.shot': 'Shot 12',
  'kit.spec.searchCast': 'Search the cast…',
  'kit.spec.anchorNote': 'The row of section links at the top of this page is the AnchorNav: it follows the section in view.',
  'kit.spec.forms.lead': 'Fields are 40 px (compact 32), the focus is an iris edge, and every message is tied to its field.',
  'kit.spec.ph.title': 'The Kite',
  'kit.spec.help.title': 'Shown on the key art and in the catalogue.',
  'kit.spec.help.locked': 'Locked: an episode of this show is finished.',
  'kit.spec.err.title': 'Give the show a title.',
  'kit.spec.err.style': 'Choose a visual style.',
  'kit.spec.err.lang': 'Choose a language.',
  'kit.spec.err.brief': 'Write a line about the story.',
  'kit.spec.err.kept': 'The earlier takes are kept.',
  'kit.spec.check': 'Keep the earlier version',
  'kit.spec.toggle': 'Hero previews',
  'kit.spec.toggleHint': 'A muted preview plays once, after 2 seconds.',
  'kit.spec.forKite': 'For The Kite',
  'kit.spec.forShow': 'For The Last Sip · Season 2',
  'kit.spec.lang': 'Arabic (Iraqi Baghdadi)',
  'kit.spec.chip1': 'Round glasses',
  'kit.spec.chip2': 'A scar over the brow',
  'kit.spec.chipPh': 'Type a mark, then Enter',
  'kit.spec.chipHelp': 'Enter or a comma adds it; Backspace in the empty field removes the last one.',
  'kit.spec.drop.picture': 'From a picture',
  'kit.spec.drop.pictureHint': 'PNG or JPEG, 512 px or more',
  'kit.spec.drop.sleeve': 'Sleeve artwork',
  'kit.spec.drop.plate': 'A photo of the place',
  'kit.spec.drop.audio': 'The song file',
  'kit.spec.drop.refused': 'SVG and GIF are refused. Choose a PNG or a JPEG.',
  'kit.spec.estimate': 'About a minute.',
  'kit.spec.choices.lead': 'One Tab stop per group; the arrow keys move the choice. A disabled choice says why, in words.',
  'kit.spec.day': 'Day',
  'kit.spec.dusk': 'Dusk',
  'kit.spec.night': 'Night',
  'kit.spec.songVideo': 'Song or video',
  'kit.spec.song': 'Song',
  'kit.spec.video': 'Video',
  'kit.spec.noCut': 'No cut yet',
  'kit.spec.startLabel': 'How do you want to start the character?',
  'kit.spec.tile.describe': 'Describe them',
  'kit.spec.tile.describeHint': 'A line about who they are.',
  'kit.spec.tile.sheet': 'Fill in a sheet',
  'kit.spec.tile.sheetHint': 'Name, look and voice, field by field.',
  'kit.spec.tile.needEngine': 'Needs the image engine, which is not running.',
  'kit.spec.overlays.lead': 'Esc closes the innermost layer and focus goes back to what opened it. No blur, no glow.',
  'kit.spec.open.dialog': 'Open a dialog',
  'kit.spec.open.confirm': 'Delete a show…',
  'kit.spec.open.ask': 'Reject a take…',
  'kit.spec.open.drawer': 'Open the activity drawer',
  'kit.spec.dlg.title': 'Rename the show',
  'kit.spec.dlg.desc': 'The new title shows everywhere the show appears.',
  'kit.spec.confirm.title': 'Delete “{name}”?',
  'kit.spec.confirm.body': 'Its seasons, episodes and shots go with it.',
  'kit.spec.confirm.keep': 'Its characters and locations stay in the studio.',
  'kit.spec.ask.title': 'Reject Take 2?',
  'kit.spec.ask.label': 'Why? The next take avoids it.',
  'kit.spec.ask.confirm': 'Reject',
  'kit.spec.ask.answer': 'The answer: {text}',
  'kit.spec.drawer.title': 'Activity',
  'kit.spec.drawer.l1': 'Drawing the frames of Episode 3',
  'kit.spec.drawer.l2': 'The story of Episode 2 was approved',
  'kit.spec.drawer.l3': 'Take 4 of shot 12 did not pass the check',
  'kit.spec.popover': 'Filter',
  'kit.spec.popoverBody': 'A popover holds a few controls and closes on Esc or a click outside.',
  'kit.spec.menu.editHint': 'Title, logline and style',
  'kit.spec.menu.export': 'Export',
  'kit.spec.menu.autoHint': 'Let the studio propose — you review it before anything is made',
  'kit.spec.menu.manualHint': 'Start from a title; every other field has a default',
  'kit.spec.toast.ok': 'Show a toast',
  'kit.spec.toast.undo': 'Show a toast with Undo',
  'kit.spec.toast.bad': 'Show an error toast',
  'kit.spec.toast.archived': 'Moved to the archive.',
  'kit.spec.toast.restored': 'Back where it was.',
  'kit.spec.toast.error': 'The take was not saved. Your changes are still here.',
  'kit.spec.pal.newShow': 'New show',
  'kit.spec.pal.contrast': 'Contrast: More',
  'kit.spec.states.lead': 'An empty page is a title card in its own shape and one sentence that is not the lead. Raw errors stay inside Details.',
  'kit.spec.slot.titleCard': 'Title card (media kit)',
  'kit.spec.slot.hero': 'Hero (media kit)',
  'kit.spec.empty.page': 'Your first show will stand here. Start with one line, or write it yourself.',
  'kit.spec.empty.section': 'No locations are chosen for this episode yet.',
  'kit.spec.empty.action': 'Choose locations',
  'kit.spec.loadingKeyArt': 'Loading the key art',
  'kit.spec.episode4': 'Episode 4',
  'kit.spec.cutMissing': 'cut missing',
  'kit.spec.shotsChosen': '18 of 20 shots chosen',
  'kit.spec.notice.info': 'Drafts are kept for this session.',
  'kit.spec.notice.ok': 'Episode 3 is ready to screen.',
  'kit.spec.notice.warn': 'This character is in two videos: the look is kept.',
  'kit.spec.notice.bad': 'The song could not be read.',
  'kit.spec.approval.lead': 'The thing to approve sits inline; the decision beside it. After Approve, one line with Undo for 10 seconds.',
  'kit.spec.approval.title': 'The Kite — Episode 4',
  'kit.spec.approval.from': 'Story Development handed it over · 12 min ago',
  'kit.spec.approval.ask': 'Approve the story to start storyboarding.',
  'kit.spec.approval.askFrames': 'Approve the frames to start producing.',
  'kit.spec.approval.excerpt': 'Abu Samir’s café, at dusk. The radio crackles; Amina turns the dial until a voice answers. “Is anyone still listening?”',
  'kit.spec.frameAlt': 'Storyboard frame {n}',
  'kit.spec.headers.lead': 'The page header has fixed places. The compact header appears once the hero has scrolled away, or stays, in the cutting room.',
  'kit.spec.header.eyebrow': 'Cast & world',
  'kit.spec.header.lead': 'Everyone who can be cast, each with one image and one voice.',
  'kit.spec.newChar': 'New character',
  'kit.spec.lobby': 'lobby',
  'kit.spec.cutting': 'cutting room',
  'kit.spec.scrollbox': 'A scrolling example',
  'kit.spec.scrollHint': 'Scroll this box up: the compact header leaves when the hero comes back, and returns when the hero goes.',
  'kit.spec.backShows': 'Back to Shows',
  'kit.spec.continue': 'Continue: Storyboard',
  'kit.spec.creation.lead': 'One layout for every new thing: the method, the one essential input, the settings in one line, and the time it takes.',
  'kit.spec.backTo': 'Back to The Last Sip · Season 2',
  'kit.spec.newEpisode': 'New episode',
  'kit.spec.creation.slate': 'For The Last Sip · Season 2 · Cartoon · Arabic (Iraqi)',
  'kit.spec.brief': 'What happens in this episode?',
  'kit.spec.briefPh': 'A line is enough.',
  'kit.spec.propose': 'Propose',
  'kit.spec.length': 'Length',
  'kit.spec.len3': '3 min',
  'kit.spec.len6': '6 min',
  'kit.spec.len10': '10 min',
  'kit.spec.step.identity': 'Identity',
  'kit.spec.step.look': 'Look',
  'kit.spec.made': 'Episode 4 was made. Next: approve its story.',
  'kit.spec.made.next': 'Open the story',
  // ---- media ---------------------------------------------------------------------------------------------------------
  // players
  'player.audio': 'Audio',
  'player.video': 'Video',
  'player.song': 'Song',
  'player.volume': 'Volume',
  'player.mute': 'Mute',
  'player.unmute': 'Unmute',
  'player.replay': 'Replay',
  'player.loading': 'Loading the file…',
  'player.captions': 'Captions',
  'player.fullscreen': 'Fullscreen',
  'player.exitFullscreen': 'Exit fullscreen',
  'player.prevFrame': 'Previous frame',
  'player.nextFrame': 'Next frame',
  'player.noTake.hint': 'A take appears here once one exists. Generate one from the shot, or upload a clip.',

  // ---- v4 (F3): frames and title cards (§5.4) ----------------------------------------------------------------
  'media.alt.keyArt': 'Key art for {title}',
  'media.alt.poster': 'Poster for {title}',
  'media.alt.sleeve': 'Cover art for {title}',
  'media.alt.figure': 'Full-length image of {name}',
  'media.alt.plate': 'Master plate of {name}',
  'media.alt.still': 'Still from {title}',

  // ---- tiles, rail, cast (§5.5–5.8) ----------------------------------------------------------------------------
  'media.play': 'Play {title}',
  'media.pause': 'Pause {title}',
  'media.selected': 'Selected',
  'media.loading': 'Loading…',
  'media.duration': 'Duration {t}',
  'media.rail.prev': 'Previous items',
  'media.rail.next': 'Next items',
  'media.rail.seeAll': 'See all',
  'media.cast.voice': 'Play the voice of {name}',
  'media.cast.voicePause': 'Pause the voice of {name}',
  'media.cast.more': 'The whole cast',
  'media.cast.leads': 'Leads',
  'media.cast.supporting': 'Supporting',

  // ---- episodes (§5.7) -------------------------------------------------------------------------------------------
  'media.episode': 'Episode {n}',
  'media.episode.play': 'Play Episode {n}',
  'media.season': 'Season {n}',
  'media.season.episodes': '{n} episode|{n} episodes',
  'media.season.choose': 'Choose a season',
  'media.season.new': 'New season',
  'media.season.propose': 'Let the studio propose',
  'media.season.write': 'Write it yourself',

  // ---- heroes (§5.3) ---------------------------------------------------------------------------------------------
  'media.hero.more': 'More',
  'media.hero.less': 'Less',
  'media.hero.pausePreview': 'Pause preview',
  'media.hero.playPreview': 'Play preview',
  'media.hero.watchWithSound': 'Watch with sound',
  'media.hero.nowScreening': 'Now screening',
  'media.hero.back': 'Back to {area}',

  // ---- the player family (§5.12) ---------------------------------------------------------------------------------
  'media.player.transport': 'Playback controls',
  'media.player.back5': 'Back 5 seconds',
  'media.player.fwd5': 'Forward 5 seconds',
  'media.player.markIn': 'Mark in',
  'media.player.markOut': 'Mark out',
  'media.player.clearMarks': 'Clear marks',
  'media.player.fit': 'Fit',
  'media.player.actualSize': 'Actual size',
  'media.player.timecode': 'Timecode',
  'media.player.failed': 'This clip didn’t load.',
  'media.player.tryAgain': 'Try again',
  'media.player.openFile': 'Open the file',
  'media.player.addNote': 'Add a note at the playhead',
  'media.player.notes': 'Notes on the timeline',
  'media.compare.label': 'Compare {a} and {b}',
  'media.compare.show': 'Show',
  'media.compare.choose': 'Choose {x}',
  'media.compare.chosen': 'chosen',
  'media.compare.heard': 'Sound from {x}',
  'media.reel.label': 'Storyboard reel · not a cut',
  'media.reel.player': 'Storyboard reel',
  'media.shot': 'Shot {n}',
  'media.strip.label': 'Shots in order',
  'media.strip.noFrame': 'Shot {n}, no frame yet',
  'media.dual.label': 'The whole programme',
  'media.dual.window': 'Part shown below',
  'media.dual.earlier': 'Show an earlier part',
  'media.dual.later': 'Show a later part',
  'media.bar.label': 'Now playing',
  'media.bar.close': 'Close the player',

  // ---- music (§5.13) ---------------------------------------------------------------------------------------------
  'media.mode.label': 'Song or video',
  'media.mode.song': 'Song',
  'media.mode.video': 'Video',
  'media.mode.noCut': 'No cut yet',
  'media.sections.caption': 'Sections of the song',
  'media.sections.section': 'Section',
  'media.sections.singer': 'Singer',
  'media.sections.shots': 'Shots',
  'media.sections.time': 'Time',
  'media.sections.playFrom': 'Play from {name}',
  'media.sections.nowSung': 'Being sung now',
  'media.sections.of': '{a} of {b}',
  'media.count.sections': '{n} section|{n} sections',
  'media.count.shots': '{n} shot|{n} shots',
  'media.songVersion': 'song version {n}',
  'media.lyrics.label': 'Lyrics',
  'media.lyrics.back': 'Back to the playhead',
  'media.lyrics.line': 'Line {n}',
  'media.lyrics.singer': 'Singer of line {n}',
  'media.lyrics.noSinger': 'No singer',
  'media.lyrics.earlier': 'Start 0.1 s earlier',
  'media.lyrics.later': 'Start 0.1 s later',
  'media.lyrics.start': 'Start (seconds)',
  'media.lyrics.text': 'Text of line {n}',
  'media.voice.play': 'Play the voice: {name}',
  'media.voice.pause': 'Pause the voice: {name}',
  'media.wave.label': 'Waveform',
  'media.wave.unavailable': 'The waveform could not be drawn from this file.',

  // ---- timeline (§5.14) ------------------------------------------------------------------------------------------
  'media.tl.label': 'Timeline',
  'media.tl.ruler': 'Ruler: click to move the playhead',
  'media.tl.picture': 'Picture',
  'media.tl.dialogue': 'Dialogue',
  'media.tl.music': 'Music',
  'media.tl.zoomIn': 'Zoom in',
  'media.tl.zoomOut': 'Zoom out',
  'media.tl.fit': 'Fit',
  'media.tl.trimStart': 'Start of shot {n}',
  'media.tl.trimEnd': 'End of shot {n}',
  'media.tl.startEarlier': 'Start 1 frame earlier',
  'media.tl.startLater': 'Start 1 frame later',
  'media.tl.endEarlier': 'End 1 frame earlier',
  'media.tl.endLater': 'End 1 frame later',
  'media.tl.selected': '{n} selected',

  // ---- cutting-room kit (§5.20) ---------------------------------------------------------------------------------
  'media.dock.resize': 'Resize {panel}',
  'media.dock.collapse': 'Collapse {panel}',
  'media.dock.expand': 'Expand {panel}',
  'media.dock.open': 'Open {panel}',
  'media.dock.close': 'Close {panel}',
  'media.dock.reset': 'Reset layout',
  'media.dock.layout': 'Layout',
  'media.dock.panes': 'Show',
  'media.inspector.mixed': 'Mixed',
  'media.inspector.count': '{n} items selected',
  'media.inspector.details': 'Details',
  'media.inspector.empty': 'Select something to see its details here.',
  'media.focus.label': 'Focus mode',
  'media.focus.on': 'Focus mode on. Press Esc to leave it.',
  'media.focus.off': 'Focus mode off.',
  'media.versions.label': 'Versions',
  'media.versions.version': 'Version {n}',
  'media.versions.current': 'current',
  'media.versions.compare': 'Compare',
  'media.versions.pickTwo': 'Pick two versions to compare.',
  'media.versions.cancel': 'Cancel',
  'media.tools.label': 'Tools',

  // ---- the specimen sections of the dev-only /kit page (components/media/Specimens.tsx) ------------------------
  'media.spec.title': 'Media, players and the cutting room',
  'media.spec.lead': 'Every part of the media kit in its states, on the bundled sample media. A page for development.',
  'media.spec.media': 'Media',
  'media.spec.players': 'Players',
  'media.spec.edit': 'Cutting room',
  'media.spec.frames': 'Frames and title cards',
  'media.spec.slates': 'Slates, stage meters and faces',
  'media.spec.tiles': 'Tiles',
  'media.spec.rails': 'Rail',
  'media.spec.episodes': 'Episodes',
  'media.spec.cast': 'Cast',
  'media.spec.heroes': 'Heroes',
  'media.spec.compact': 'Compact header',
  'media.spec.hero.backdrop': 'Backdrop hero · Show page',
  'media.spec.hero.diptych': 'Diptych hero · Short Overview',
  'media.spec.hero.episode': 'Diptych without a poster · Episode Overview',
  'media.spec.hero.sleeve': 'Sleeve hero · Music video',
  'media.spec.hero.figure': 'Figure hero · Character profile',
  'media.spec.hero.plate': 'Plate hero · Location page',
  'media.spec.hero.theatre': 'Theatre hero · Screening Room',
  'media.spec.neutral': 'Neutral: no presentation data',
  'media.spec.tinted': 'With an example tint',
  'media.spec.ready': 'Ready',
  'media.spec.drawing': 'Drawing',
  'media.spec.missing': 'No picture',
  'media.spec.unavailable': 'File missing',
  'media.spec.letterbox': 'Letterboxed on its own edge colour',
  'media.spec.selected': 'Selected, in a picker',
  'media.spec.phase': 'Drawing Hana · 2nd in the queue',
  'media.spec.inline': 'Inline player',
  'media.spec.preview': 'Hero preview (muted, once, after 2 s)',
  'media.spec.canvas': 'Canvas player',
  'media.spec.theatre': 'Theatre player',
  'media.spec.bar': 'Player bar',
  'media.spec.bar.show': 'Show the fixed player bar',
  'media.spec.bar.hide': 'Hide the fixed player bar',
  'media.spec.music': 'Song transport, sections and lyrics',
  'media.spec.voice': 'Voice reel and waveform',
  'media.spec.failed': 'A clip that did not load',
  'media.spec.strips': 'Film strips',
  'media.spec.dual': 'Dual-scale strip',
  'media.spec.reel': 'Storyboard reel',
  'media.spec.compare': 'Compare A/B',
  'media.spec.timeline': 'Timeline',
  'media.spec.dock': 'Docked workspace',
  'media.spec.inspector': 'Inspector',
  'media.spec.versions': 'Version stack and tool row',
  'media.spec.frame': 'Frame',
  'media.spec.shots': 'Shots',
  'media.spec.details': 'Details',
  'media.spec.st.waiting': 'Waiting for you',
  'media.spec.st.oneWaiting': '1 waiting for you',
  'media.spec.st.storyboard': 'Storyboard · 12 of 20 frames',
  'media.spec.st.producing': 'Producing · shot 7 of 20',
  'media.spec.st.finished': 'Finished',
  'media.spec.st.finalCut': 'Final cut ready',
  'media.spec.st.approved': 'Approved',
  'media.spec.st.draft': 'Draft — awaiting your approval',
  'media.spec.st.noImage': 'No image yet',
  'media.spec.st.story': 'Story',
  'media.spec.f.show': 'Show',
  'media.spec.f.short': 'Short',
  'media.spec.f.musicVideo': 'Music video',
  'media.spec.f.character': 'Character',
  'media.spec.f.location': 'Location',
  'media.spec.f.seasons': '2 seasons',
  'media.spec.f.episodes': '3 episodes',
  'media.spec.f.iraqi': 'Arabic (Iraqi)',
  'media.spec.f.english': 'English',
  'media.spec.f.voice': 'Voice',
  'media.spec.f.noVoice': 'No voice',
  'media.spec.f.exterior': 'Exterior',
  'media.spec.f.interior': 'Interior',
  'media.spec.f.lighting': 'Morning · Afternoon · Night',
  'media.spec.f.used': 'in 2 productions',
  'media.spec.f.min': '{n} min',
  'media.spec.f.cut': 'Cut {n}',
  'media.spec.f.daysAgo': '2 days ago',
  'media.spec.f.inEpisodes': 'in 3 episodes · S1',
  'media.spec.f.sings': 'sings 2 of 4 sections',
  'media.spec.f.studioVoice': 'Studio-designed synthetic voice',
  'media.spec.f.recording': 'Recording — sample',
  'media.spec.a.continue': 'Continue: Storyboard',
  'media.spec.a.continueEp': 'Continue S1 · E2: Produce',
  'media.spec.a.playCut': 'Play cut',
  'media.spec.a.approve': 'Approve',
  'media.spec.a.redraw': 'Redraw',
  'media.spec.a.edit': 'Edit',
  'media.spec.a.use': 'Use in a production',
  'media.spec.a.download': 'Download',
  'media.spec.a.split': 'Split',
  'media.spec.a.trim': 'Trim',
  'media.spec.a.note': 'Note',
  'media.spec.light.day': 'Day',
  'media.spec.light.night': 'Night',
  'media.spec.light.label': 'Lighting',
  'media.spec.saved': 'Saved',

  // ---- production menu (ProductionTile) --------------------------------------------------------------------------
  'media.delete.title': 'Delete “{title}”?',
  'media.delete.body': 'Its story, shots and takes go with it. Characters, locations and files stay in the studio.',
  // ---- shell ---------------------------------------------------------------------------------------------------------
  // navigation
  'nav.shows': 'Shows',
  'nav.shorts': 'Shorts',
  'nav.musicVideos': 'Music Videos',
  'nav.characters': 'Characters',
  'nav.locations': 'Locations',
  'nav.assets': 'Asset Library',
  'nav.settings': 'Settings',
  'nav.more': 'More',
  'app.name': 'Vewbox Studio',

  // home
  // the restored shell

  // the six areas and the studio organisation
  'nav.company': 'Studio Company',
  'nav.production': 'Production',
  'projects.title': 'Projects',
  'library.title': 'Library',
  // navigation and the production page
  'nav.new': 'New…',
  'nav.files': 'Files',

  // ---- v4: page titles (§7.3; src/components/shell/titles.ts) ----
  'shell.title.episode': 'Episode {n}',
  'shell.title.season': 'Season {n}',
  'shell.title.shot': 'Shot {n}',
  'shell.title.newLocation': 'New location',
  'shell.title.kitMedia': 'Media kit',

  // ---- v4: the shell (§5.1, §7.1) ----
  'shell.help': 'Help & shortcuts',
  // SaveState (audit D1): what the store's queue says, never assumed
  // the connection (the event stream) and what the studio is running, from the job list
  // ServerBar: only when the event stream has really dropped
  'shell.server.down': 'Can’t reach the studio server.',
  'shell.server.since': 'Showing what was there {ago}.',
  'shell.server.justNow': 'Showing what was there a moment ago.',
  'shell.server.nothing': 'Nothing could be loaded yet.',
  'shell.server.retry': 'Try now',
  'shell.lastKnown': 'Last known',
  // the error and loading states of every page
  'shell.error.title': 'This page stopped working.',
  'shell.error.hint': 'What the studio holds is not affected. Try the page again; the details below say what broke.',
  'shell.error.retry': 'Try again',
  'shell.error.details': 'Details',
  'shell.error.home': 'Go to Home',

  // ---- v4: the command palette (§5.17, §7.6) ----
  'shell.palette.title': 'Command palette',
  'shell.palette.label': 'Search the studio',
  'shell.palette.placeholder': 'Go to, create, decide…',
  'shell.palette.group.recent': 'Recent',
  'shell.palette.group.goto': 'Go to',
  'shell.palette.group.create': 'Create',
  'shell.palette.group.decide': 'Decide',
  'shell.palette.group.settings': 'Settings',
  'shell.palette.none': 'Nothing matches “{q}”.',
  'shell.palette.count': '{n} result|{n} results',
  'shell.palette.hint': '↑ ↓ to move · Enter to open · Esc to close',
  'shell.palette.kind.page': 'Page',
  'shell.palette.kind.character': 'Character',
  'shell.palette.kind.location': 'Location',
  'shell.palette.kind.department': 'Department',
  'shell.palette.kind.approve': 'Approve',
  'shell.palette.kind.setting': 'Setting',
  'shell.palette.new.show': 'New show',
  'shell.palette.new.season': 'New season',
  'shell.palette.new.episode': 'New episode',
  'shell.palette.new.short': 'New short',
  'shell.palette.new.musicVideo': 'New music video',
  'shell.palette.new.character': 'New character',
  'shell.palette.new.location': 'New location',
  'shell.palette.propose': 'Let the studio propose',
  'shell.palette.write': 'Write it yourself',
  'shell.palette.describePlace': 'Describe the place',
  'shell.palette.decide.stage': '{stage} of {title}',
  'shell.palette.decide.image': 'Picture of {name}',
  // B8: the other kinds of decision (docs/CONTRACTS-REDESIGN-BACKEND.md)
  'shell.palette.kind.review': 'Review',
  'shell.palette.decide.line': '1 line to hear again in {title}',
  'shell.palette.decide.lines': '{n} lines to hear again in {title}',
  'shell.palette.decide.take': 'Take to review in {title}',
  'shell.palette.decide.pass': 'Production pass of {title}',
  'shell.palette.contrastMore': 'Contrast: More',
  'shell.palette.contrastStandard': 'Contrast: Standard',
  'shell.palette.motionOn': 'Reduce motion: On',
  'shell.palette.motionOff': 'Reduce motion: Off',
  'shell.palette.keysOn': 'Single-key shortcuts: On',
  'shell.palette.keysOff': 'Single-key shortcuts: Off',

  // ---- v4: the shortcut sheet (§5.17, §7.5) ----
  'shell.keys.title': 'Keyboard shortcuts',
  'shell.keys.or': 'or',
  'shell.keys.global': 'Global',
  'shell.keys.global.hint': 'Anywhere, except while typing in a field.',
  'shell.keys.player': 'Player',
  'shell.keys.player.hint': 'While a player has focus.',
  'shell.keys.storyboard': 'Storyboard',
  'shell.keys.storyboard.hint': 'While the film strip or the board has focus.',
  'shell.keys.timeline': 'Timeline',
  'shell.keys.timeline.hint': 'In the cutting room’s timeline.',
  'shell.keys.palette': 'Open the command palette',
  'shell.keys.sheet': 'Show these shortcuts',
  'shell.keys.collapse': 'Collapse or expand the navigation',
  'shell.keys.focus': 'Focus mode, in the cutting room',
  'shell.keys.esc': 'Close the innermost layer',
  'shell.keys.play': 'Play or pause',
  'shell.keys.jump': '5 seconds back or forward',
  'shell.keys.frame': 'One frame back or forward',
  'shell.keys.second': 'One second back or forward',
  'shell.keys.ends': 'Go to the start or the end',
  'shell.keys.mute': 'Mute or unmute',
  'shell.keys.captions': 'Captions on or off',
  'shell.keys.fullscreen': 'Full screen',
  'shell.keys.marks': 'Mark in or out, in the cutting room',
  'shell.keys.compare': 'Show A or B while comparing',
  'shell.keys.frames': 'Move between frames',
  'shell.keys.reorder': 'Move the shot earlier or later',
  'shell.keys.range': 'Select a run of clips',
  'shell.keys.toggleClip': 'Add a clip to the selection, or take it out',
  'shell.keys.zoom': 'Zoom the timeline',
  'shell.keys.pref': 'Single-key shortcuts',
  'shell.keys.pref.hint': 'Keys pressed without Ctrl or ⌘, such as ? and F and the player’s keys. Turn them off if they get in the way of a screen reader or voice control.',
  'shell.key.space': 'Space',
  'shell.key.click': 'Click',
  'shell.key.scroll': 'Scroll',
  // ---- shows ---------------------------------------------------------------------------------------------------------
  // wizard
  'wizard.moreSettings': 'More settings',
  'wizard.createProject': 'Create Project',
  'wizard.lookAndFormat': 'Look and format',
  'wizard.people': 'Who is in it, and where',
  'wizard.optional': 'optional',
  'wizard.newShow': 'New Show',
  'wizard.newEpisode': 'New Episode',
  'wizard.newShort': 'New Short',
  'wizard.newMusicVideo': 'New Music Video',
  'wizard.inherits': 'Inherits the show’s look, language and cast. Change anything here for this episode only.',
  'wizard.needTitle': 'Give it a title or describe the idea.',
  'wizard.song': 'The song',
  'wizard.generateSong': 'Generate Song',
  'wizard.generateSong.hint': 'Describe the song and write its lyrics.',
  'wizard.uploadSong': 'Upload Song',
  'wizard.uploadSong.hint': 'Use your own track.',
  'wizard.songCaption': 'Describe the song',
  'wizard.songCaption.help': 'Genre, mood, tempo, instruments, voice.',
  'wizard.lyrics': 'Lyrics',
  'wizard.lyrics.help': 'Leave a blank line between sections. Start a section with [verse], [chorus], [bridge], [intro] or [outro] to name it.',
  'wizard.singer': 'Who sings',
  'wizard.createdSong': 'The song is saved with the project. Generate the recording from the Story tab once the project exists.',
  // show workspace
  'show.backTo': 'Back to',
  // creation steps
  'step.song': 'Song',
  'step.look': 'Look & format',
  'step.people': 'Cast & places',
  'step.performers': 'Performers',
  'step.review': 'Review',
  'step.of': 'of',
  'wizard.reviewHint': 'Everything below is saved with the project and can be changed later.',
  'wizard.concept': 'Treatment',
  'new.lead': 'Choose what to make. Each opens a short wizard: the idea, the look and format, the people and places, then one button.',
  'show.world': 'World',
  // Auto Idea
  'auto.title': 'Auto Idea',
  'auto.lead': 'The studio proposes the concept, the title and premise, the cast and places, and the structure. You review and edit all of it before anything is created.',
  'auto.create': 'Create an idea for me',
  'auto.nothingRequired': 'Nothing is required.',
  'auto.showContext': 'Uses the world of',
  'auto.preferences': 'Optional preferences',
  'auto.preferencesSet': 'set',
  'auto.preferencesHint': 'Every choice starts at “let the studio decide”. What you set here takes priority.',
  'auto.decide': 'Studio decides',
  'auto.fromShow': 'From the show',
  'auto.mood': 'Mood',
  'auto.moodHelp': 'A few words, such as “warm and nocturnal”.',
  'auto.includeCast': 'Characters to include',
  'auto.includePerformers': 'Performers to include',
  'auto.includeLocations': 'Locations to include',
  'auto.includeHint': 'Optional. The studio adds the rest the story needs.',
  'auto.sampleTitle': 'Sample proposal — a written example',
  'auto.sampleBody': 'A written example, not a proposal from the story engine: it follows your preferences and, for an episode, the show’s cast and world. Nothing here was researched or generated. Edit anything, then create the project — or go back and ask the story engine for a proposal.',
  'auto.concept': 'Concept',
  'auto.premise': 'Premise',
  'auto.structure': 'Structure',
  'auto.firstEpisodes': 'First episodes',
  'auto.castHint': 'Existing characters are reused; new ones are created in the library, with no appearance yet, only if you keep them.',
  'auto.include': 'Include',
  'auto.yourChoice': 'Your choice',
  'auto.new': 'New',
  'auto.existing': 'In your library',
  'auto.another': 'Show another sample',
  'auto.backToPreferences': 'Back',
  // Manual brief
  'manual.title': 'Manual brief',
  'manual.lead': 'A title or a short description is enough to begin. Everything else has a default.',
  'manual.start': 'Write my brief',
  'manual.description': 'Description',
  'manual.descriptionHelp': 'A line or a paragraph: what happens, to whom, how it should feel.',
  'manual.defaultsHint': 'Defaults from Settings; change any of them.',
  'manual.songOptional': 'Optional. Add the song now, or later from the Song & Lyrics tab.',
  'manual.songLater': 'Add it later',
  'manual.songLater.hint': 'Start without a song.',
  'step.brief': 'Brief',
  'wizard.needSongWords': 'Describe the song or write some lyrics — or choose “Add it later”.',
  'wizard.needSongFile': 'Upload a track — or choose “Add it later”.',
  'auto.generatedTitle': 'Proposal from the story engine',
  'auto.generatedBody': 'Written for you now; everything is editable before anything is created.',
  'auto.writing': 'Writing a proposal…',
  'auto.writingHint': 'Usually under a minute. You can keep the page open.',
  'auto.failed': 'The story engine could not write a proposal.',
  'auto.useSample': 'Use a written example instead',
  'auto.writeAnother': 'Write another proposal',
  'auto.premiseLabel': 'Your idea (optional)',
  'auto.premiseHint': 'A line is enough. Leave it empty and the studio invents one.',
  'wizard.newSeason': 'New Season',
  'auto.seasonContext': 'The agents read the show’s concept, language, previous seasons, the story so far, the cast’s locked identities, the places and the open storylines, and propose a season that continues them.',
  'auto.episodeContext': 'The agents continue from the last episode’s ending and the show’s bible; the show’s language and the cast’s voices never change.',
  'auto.nextEpisodes': 'The season’s episodes',
  'season.manualHint': 'A title or a line about the season is enough; the agents develop it from the show’s continuity when its first episode is created.',
  'new.character.hint': 'A person the studio keeps: one look and one voice across every production.',
  'new.location.hint': 'A place with its plates and views, reused across productions.',
  // ---- film ----------------------------------------------------------------------------------------------------------
  // D23: what the script writer and the shot planner read, editable by the producer
  'film.scene.purpose': 'What the scene is for',
  'film.scene.purposeHelp': 'The script and the shot plan are written from this. Correct it before writing the script.',
  'film.brief.promiseHelp': 'The story’s promise: how it opens and how it ends. Every later step of the story keeps to it.',
  'film.brief.hook': 'The opening',
  'film.brief.ending': 'The ending',
  // next steps
  'next.writeStory': 'Write the story',
  'next.chooseCast': 'Choose the cast',
  'next.writeScript': 'Write the script',
  'next.planShots': 'Plan the shots',
  'next.chooseTakes': 'Choose takes',
  'next.reviewCut': 'Review the cut',
  'produce.sampleNote': 'The takes here are sample clips. Generate makes real ones; they cannot be exported as yours.',

  // story
  'story.brief': 'The brief',
  'story.script': 'Script',
  'story.lines': 'lines',
  'story.present': 'Present',
  'story.autoIdea': 'Started from Auto Idea',
  'story.autoIdea.example': 'Started from Auto Idea (the written example)',
  'story.manual': 'Started from your brief',
  'story.writeHint': 'Write the story in your own words, or let "Develop the story" draft it from the brief; every edit is yours.',

  // storyboard
  'board.shotsIn': 'shots',
  'board.noFrame': 'No opening frame',
  'board.dragHint': 'Drag shots to reorder within a scene.',
  'board.editShot': 'Edit shot',
  'board.planned': 'planned',
  'board.framed': 'framed',
  'board.filmed': 'with takes',
  'board.chosen': 'chosen',

  // produce
  'produce.lead': 'Frames and takes for every shot. Choose the take that goes into the cut.',
  'produce.selectedTake': 'Selected take',
  'produce.chooseTake': 'Choose a take',
  'produce.noTakes': 'No takes yet for this shot.',
  'produce.opening': 'Opening frame',
  'produce.ending': 'Ending frame',
  'produce.shotsReady': 'shots with a chosen take',

  // final cut
  'final.assembled': 'Assembled cut',
  'final.sampleCut': 'Sample cut',
  'final.noCut': 'No assembled cut yet.',
  'final.mix': 'Sound in this cut',
  'final.mix.hint': 'Every sound the cut was mixed from, where it sits and why it has that level. Each source appears once.',
  'final.mix.muted': 'take soundtrack(s) muted under the song master.',
  'final.sequence': 'Sequence',
  'final.export': 'Export',
  'final.missing': 'shots still need a chosen take',
  'final.sound': 'Sound',
  'final.dialogueTrack': 'Dialogue',
  'final.musicTrack': 'Music',
  'final.ambienceTrack': 'Ambience',

  // shot editor
  'shot.whatHappens': 'What happens',
  'shot.references': 'References',
  'shot.advanced': 'Advanced',
  'shot.opening': 'Opening frame',
  'shot.ending': 'Ending frame',
  'shot.previous': 'Previous shot',
  'shot.nextShot': 'Next shot',
  'shot.backToBoard': 'Back to storyboard',
  'shot.unsaved': 'Unsaved changes',
  'shot.leave': 'You have unsaved changes. Leave anyway?',
  'shot.deleteConfirm': 'Delete this shot and its takes?',
  'gen.started': 'Started. Progress shows in Activity.',
  'gen.failed': 'Could not start',
  'gen.writeStory': 'Develop the story',
  'gen.writeStory.hint': 'From the brief: logline, synopsis, new characters and places, and the scene breakdown.',
  'gen.writeScript': 'Write the script',
  'gen.planShots': 'Plan the shots',
  'gen.replanShots': 'Replan the shots',
  'gen.replanConfirm': 'This scene already has takes. Replanning replaces its shots and their takes stay only in the library. Continue?',
  'gen.frames': 'Prepare frames',
  'gen.take': 'Generate video',
  'gen.anotherTake': 'Another take',
  'gen.produceAll': 'Produce every shot',
  'gen.produceAll.hint': 'Draws missing frames, generates a take for each shot without one, then assembles the cut.',
  'gen.assemble': 'Assemble the cut',
  'gen.export': 'Export',
  'gen.plates': 'Draw plates',
  'gen.voiceBuild': 'Build the voice',
  'gen.dialogue': 'Record the dialogue',
  'gen.dialogue.hint': 'Speaks every line with its character’s studio voice and checks each one by transcription. The cut uses these recordings for takes without their own sound (uploaded clips); MiniMax takes speak natively.', // v4-lint: allow engine — pre-existing copy that names an engine; the page package that rewrites this page writes it engine-free (Produce)
  'produce.linesVoiced': 'lines recorded',
  'gen.song': 'Generate the song',
  'gen.respeak': 'Re-record speaking shots',
  'gen.respeak.hint': 'New takes for the speaking shots whose chosen take was never checked against the script: each line is recorded first with the character’s voice, the shot is cut to its words, and the clip is transcribed back; a passing take becomes the choice.',
  'gen.performance': 'Assign the singing',
  'gen.performance.hint': 'Decides who sings each section (solo, duet, alternating, instrumental) from the lyrics and the story, and copies it onto the planned shots. Only the assigned performer sings in a shot.',
  'gen.rejectTake': 'Reject',
  'gen.rejectReason': 'Why is this take rejected?',
  'gen.rejected': 'Rejected',
  'gen.qaFailed': 'Automatic checks failed',
  'gen.qaPassed': 'Checks passed',
  'gen.provenance': 'How it was made',
  'gen.model': 'Model',
  'gen.request': 'Request',
  'gen.prompt': 'Prompt',
  'gen.cost': 'Cost',
  'gen.time': 'Generation time',
  'gen.editPrompt': 'Prompt for this shot',
  'gen.editPrompt.hint': 'Written by the studio from the shot; edit it and the next take uses your words.',
  'final.measured': 'Measured loudness of the cut',
  'final.target': 'Loudness target',
  'final.truePeak': 'true peak',
  'final.mixTargets': 'mix: dialogue 0 dB, music −14 dB, ambience −12 dB',
  'take.upload': 'Upload a clip',
  'take.upload.hint': 'A video file becomes a take of this shot (MP4, MOV or WebM). The people in the shot count as having appeared in a video.',
  'take.uploaded': 'Clip added as a take.',
  'final.exportsTitle': 'Exports',
  'final.download': 'Download',
  'final.subtitles': 'Subtitles',
  'final.exportStarted': 'Export started. The file appears here when it is ready.',
  'final.realCut': 'Assembled from the chosen takes',
  'final.needsRealTakes': 'Some chosen takes are sample clips. Generate real takes first.',
  'gate.story': 'The story needs your approval before production starts',
  'gate.story.hint': 'Read the scenes and the script; approve when they are what you want made. Nothing is generated before that.',
  'gate.cut': 'The cut needs your approval before it is exported',
  'gate.cut.hint': 'Watch the assembled cut; approve it to unlock the export.',
  'gate.approved': 'Approved',
  'gate.by': 'by',
  'gate.changesRequested': 'Changes were requested',
  // ---- music ---------------------------------------------------------------------------------------------------------
  // songs
  'song.title': 'Song',
  'song.generated': 'Generated song',
  'song.notRecorded': 'Not recorded yet',
  'song.uploaded': 'Uploaded track',
  'song.sections': 'Sections',
  'song.lyrics': 'Lyrics',
  'song.noSong': 'No song yet.',
  'song.replace': 'Replace song',
  // music video workspace
  'mv.lyrics.hint': 'Write the lyrics as sections. Select a section to set who sings it and when.',
  'mv.sectionTiming': 'Timing',
  'mv.sectionSingers': 'Sung by',
  'mv.from': 'From',
  'mv.to': 'To',
  'mv.noSection': 'Select a section to see who sings it and when.',
  'mv.performers.hint': 'Who sings and how they sound. Each performer’s voice is chosen on their character page.',
  'mv.addPerformer': 'Add performer',
  'mv.lead': 'Lead',
  'mv.sections': 'sections',
  'mv.visual.hint': 'How the song is seen: the performer on camera, a story under the song, or both.',
  'mv.concept.PERFORMANCE': 'Performance',
  'mv.concept.PERFORMANCE.hint': 'The singer on camera, in the location, for the whole song.',
  'mv.concept.NARRATIVE': 'Narrative',
  'mv.concept.NARRATIVE.hint': 'A story told under the song; the singer may never appear.',
  'mv.concept.MIXED': 'Mixed',
  'mv.concept.MIXED.hint': 'Performance cut with story; the chorus returns to the singer.',
  'mv.waveform': 'Waveform, from the audio file',
  'mv.noAudio': 'No audio yet. The song plays once a track exists.',
  'mv.nowPlaying': 'Now playing',
  'song.noWordsYet': 'No words yet — select to write them.',
  'mv.waveformUnavailable': 'The waveform could not be drawn from this file.',
  // ---- cast ----------------------------------------------------------------------------------------------------------
  // later — where generation would happen

  // characters & locations
  'char.deleteConfirm': 'Delete this character? They are removed from every cast list.',
  'loc.deleteConfirm': 'Delete this location? Scenes set here keep their other details.',
  'loc.views': 'Views and states',
  // characters & locations
  'char.voiceIdentity': 'Voice identity',
  'loc.props.hint': 'What stands in the location and can be used in a shot.',
  'loc.addProp': 'Add prop',
  'loc.lighting.hint': 'The times of day this place is seen in, and its states.',
  'loc.states': 'States',
  'loc.cameraViews': 'Camera views',
  'loc.libraryLead': 'The places your stories happen in: one master plate each, with its views and lighting.',
  // voice
  'voice.source.SAMPLE': 'Sample',
  'voice.notGenerated': 'Not generated yet. Build the voice to hear it.',
  'voice.upload': 'Upload a recording',
  'voice.added': 'Recording added.',
  'voice.notAudio': 'Choose an audio file.',
  // characters: usage and the continuity rule
  'char.usage.unused': 'Unused',
  'char.usage.unknown': 'History not on record',
  'char.usage.takeRemoved': 'take removed',
  'char.lock.short': 'Preserved: used in a video.',
  'char.lock.title': 'Appearance preserved',
  'char.lock.formHint': 'This character has been in a video, so the fields that describe how they look are kept as they are.',
  'char.lock.seeUsage': 'See where',
  'char.ref.yours': 'Your reference',
  'char.ref.upload': 'Upload a reference',
  'char.ref.replace': 'Replace',
  'char.ref.label': 'reference upload',
  'char.traits': 'Traits',
  'char.notes': 'Creative notes',
  'char.notes.hint': 'For the writers: habits, history, how to play them. Never used to draw the character.',
  'char.usedIn.assignedHint': 'Shows and productions whose cast includes this character.',
  'char.usedIn.deleted': 'deleted',
  'char.usedIn.first': 'First appeared',

  // character creation — one page, three starts
  'char.create.header': 'For whom, which look, which language',
  'char.create.forNone': 'The library (no show yet)',
  'char.create.describe': 'Describe them',
  'char.create.sheet': 'Write the sheet',
  'char.create.picture': 'From a picture',
  'char.create.engineDown': 'Not reachable',
  'char.create.engineDownTitle': 'An engine this start needs is not reachable',
  'char.create.openEngines': 'Settings → Engines',
  'char.create.sheetAlwaysWorks': 'Write the sheet always works; the look can be drawn once the engine is back.',
  'char.create.needDialect': 'Choose a dialect for an Arabic character.',
  'char.create.who': 'Who are they?',
  'char.create.whoHint': 'A line is enough: role, age, where they come from, how they carry themselves.',
  'char.create.briefPh': 'A café owner in her sixties who notices everything and says little',
  'char.create.briefEmpty': 'Write a line about them, or at least a name.',
  'char.create.briefLong': 'Shorter: 2 000 characters at most.',
  'char.create.voiceNone': 'No voice yet',
  'char.create.voiceRecording': 'Add a recording now',
  'char.create.voiceNoneHint': 'No voice is made now. Later, on the profile’s Voice tab, the studio can design a synthetic voice from the character’s description, or build one from a recording you have permission to use. An Iraqi voice needs a real Iraqi recording.',
  'char.create.voiceRecordingHint': '3–30 seconds of the character’s voice, in their language. It is checked as soon as the character exists, and the voice is built from it as the last step.',
  'char.create.voiceRecordingWhen': 'checked once the character exists',
  'char.create.voiceRecordingNeeded': 'Choose a recording, or pick "No voice yet".',
  'char.create.rec.waiting': 'Your recording is checked as soon as the character exists',
  'char.create.rec.uploading': 'Checking your recording…',
  'char.create.rec.accepted': 'Recording accepted — the voice is built from it',
  'char.create.rec.refused': 'The recording was not accepted',
  'char.create.rec.error': 'The recording could not be checked',
  'char.create.design': 'Design character',
  'char.create.needPicture': 'Add the picture first.',
  'char.create.img.type': 'Not a usable picture: PNG, JPEG or WebP only; SVG and GIF are refused',
  'char.create.img.size': 'Too large: 20 MB at most',
  'char.create.img.minSide': 'Too small: the shortest side must be at least 512 px',
  'char.create.img.checked': 'Checked by the studio',
  'char.create.img.oneFace': 'one face',
  'char.create.img.faces': 'faces',
  'char.look.fromReference': 'from the reference picture',
  'char.create.keepFaceChangeHint': 'Write the new hair or clothes to change them; left empty they stay as in the picture.',
  'char.create.pictureLookHint': 'The look is your picture: the studio does not describe the face, hair, skin or clothes in words (it cannot see pictures), so they stay "from the reference picture" until you write them. Casting writes who they are from the name, role and your note.',
  'char.create.img.noFaceCheck': 'size and sharpness checked; the face is not checked (no face detector is installed)',
  'char.create.img.refused': 'The studio cannot use this picture',
  'char.create.keep': 'Keep from the picture',
  'char.create.keepFace': 'The face only',
  'char.create.keepAll': 'Face, hair and wardrobe',
  'char.create.keepHint': 'Fine marks, logos and the background are never kept.',
  'char.create.keepFace.prompt': 'Keep the face from the reference picture; everything else follows the sheet.',
  'char.create.keepAll.prompt': 'Keep the face, hair and wardrobe from the reference picture.',
  'char.create.keepChangeHelp': '"keep the face and hair; put her in a 1970s Baghdad café"',
  'char.create.designFromPicture': 'Design from picture',
  'char.create.noVoiceYet': 'No voice yet — make one on the profile’s Voice tab.',
  'char.create.making': 'Making the character',
  'char.create.notTheLook': 'a guide, not the appearance',
  'char.create.drawAgain': 'Draw again',
  'char.create.addRecording': 'Add a recording',
  'char.create.writeMyself': 'Write it myself',
  'char.create.partial': '{name} exists. Open the profile to finish what did not run.',
  'char.create.nothingMade': 'Nothing was created; your brief is kept.',
  'char.create.openProfile': 'Open profile',
  'char.create.leave': 'Leave without creating the character? The brief is lost.',
  'char.create.recordOnly': 'Create',
  'char.create.andDraw': 'Create and draw',
  // the sheet
  'char.form.identity': 'Identity',
  'char.form.look': 'Look',
  'char.form.needName': 'give them a name',
  'char.form.nameArHint': 'used by the Arabic voice',
  'char.form.roleHelp': 'One sentence: who they are in the story.',
  'char.form.rolePh': 'Café owner, sixty, unhurried',
  'char.form.personalityHelp': 'How they think and speak. Casting writes it when blank.',
  'char.form.speciesHelp': 'Leave blank for a person.',
  'char.form.speciesPh': 'cat',
  'char.form.lookHint': 'Every field is optional: what you leave blank, Casting decides and you can change later.',
  'char.form.voiceHint': 'How the voice should feel. The voice itself is made later on the profile’s Voice tab: designed from these words, or built from a recording you have permission to use.',
  'char.form.distinguishingHelp': 'Separate with commas: a scar, a limp, round glasses.',
  'char.form.timbrePh': 'Gravelly, warm',
  'char.form.exactAge': 'Exact age',
  'char.form.age.child': 'Child',
  'char.form.age.teen': 'Teen',
  'char.form.age.adult': 'Adult',
  'char.form.age.older': 'Older',
  'char.form.preview': 'Sheet preview',
  'char.form.unnamed': 'Unnamed',
  'char.form.previewNote': 'The words as type. The look is drawn after saving.',
  'voice.pitch.LOW': 'Low',
  'voice.pitch.MID': 'Mid',
  'voice.pitch.HIGH': 'High',
  'voice.pace.SLOW': 'Slow',
  'voice.pace.MEASURED': 'Measured',
  'voice.pace.QUICK': 'Quick',
  'voice.proofLine': 'Proof line',

  // the directory and the profile
  'char.usage.inVideos': 'In videos',
  'char.usage.unknown.hint': 'The video history of this character is not on record, so it is preserved as if it had been used.',
  'char.create.img.reason.MIN_SIDE': 'the shortest side is under 512 px',
  'char.create.img.reason.NO_FACE': 'no face was found',
  'char.create.img.reason.MANY_FACES': 'more than one face',
  'char.create.img.reason.FACE_SMALL': 'the face is too small in the frame',
  'char.create.img.reason.BLURRY': 'the picture is blurry',
  'char.created.title': 'Just created',
  // ---- characters v3: the canonical image, the cast profile, the voice identity, creation (CONTRACTS-IDENTITY-PACK.md v2; DESIGN-SYSTEM-V3 §9.4–9.7) ----
  'cast.status.draft': 'Draft',
  'cast.status.approved': 'Approved',
  'cast.status.locked': 'Locked',
  'cast.status.none': 'No image yet',
  'cast.status.legacy': 'Older portrait',
  'cast.status.legacyLong': 'Older portrait — no canonical image yet',
  'cast.status.draftLong': 'Draft — awaiting your approval',
  'cast.status.approvedLong': 'Approved',
  'cast.status.lockedUsed': 'Locked: used in {n} videos',
  'cast.status.lockedUsedOne': 'Locked: used in 1 video',
  'cast.status.lockedUnknown': 'Locked: video history not on record',
  'cast.status.noneLong': 'No image yet',
  'cast.lock.usedWhy': 'The image and the voice are kept as they were filmed, for continuity. Name, description, personality and notes can still be edited.',
  'cast.lock.unknownWhy': 'Its video history is not on record, so it is kept as if it had been filmed. Name, description, personality and notes can still be edited.',
  'cast.image.none': 'No image yet',
  'cast.image.alt': '{name}, full length, from the front',
  'cast.image.drawing': 'Drawing the image…',
  'cast.image.version': 'Version',
  'cast.image.noneHint': 'One full-length image from the front becomes the character’s identity everywhere.',
  'cast.image.legacyHint': 'This character has an older close-up portrait. Draw the full-length image to give them a canonical identity.',
  'cast.image.draftHint': 'Check the face, the clothes and the whole figure. Once approved, this image is used everywhere the character appears.',
  'cast.image.checkFailed': 'The automatic check flagged this image',
  'cast.image.approve': 'Approve image',
  'cast.image.approved': 'Image approved',
  'cast.image.approveAnyway': 'Approve anyway',
  'cast.image.overrideLabel': 'Why is it right despite the check?',
  'cast.image.overrideHelp': 'Your reason is recorded with the approval.',
  'cast.image.waitDrawing': 'Approve once the new drawing has finished.',
  'cast.image.redraw': 'Redraw',
  'cast.image.draw': 'Draw the image',
  'cast.redraw.title': 'Redraw the image',
  'cast.redraw.lead': 'A new version is drawn and waits as a draft for your approval. The current image is kept as an earlier version and is not shown.',
  'cast.redraw.reference': 'Reference picture',
  'cast.redraw.withReference': 'The new image follows this picture; it is not the image itself.',
  'cast.redraw.fromDescription': 'Without a picture, the image is drawn from the written look.',
  'cast.loc.redraw': 'Redraw the place',
  'cast.loc.redrawConfirm': 'Draw a new master plate and new views from the description? The current plates stay in the library.',
  'cast.redraw.fromEarlierPicture': 'Without a new picture, the image is drawn again from the reference picture this character was made from.',
  'cast.redraw.go': 'Redraw image',
  'cast.profile.noDescription': 'No description yet.',
  'cast.profile.look': 'The look, in words',
  'cast.profile.who': 'Who',
  'cast.profile.delete': 'Delete character',
  'cast.edit.details': 'Edit details',
  'cast.edit.detailsHint': 'Name, description and personality stay editable even after the character has been filmed.',
  'cast.edit.description': 'Short description',
  'cast.edit.languageHint': 'The language and dialect choose the voice engine.',
  'cast.edit.languageLocked': 'The language is kept: the character has spoken in a video with this voice.',
  'cast.edit.look': 'Edit look',
  'cast.edit.lookHint': 'How they look, in words. Casting draws from these.',
  'cast.edit.lookRedraw': 'Saving does not change the image: redraw it to apply a new look.',
  'cast.edit.voiceTraits': 'How the voice should sound',
  'cast.card.voice': 'Voice',
  'cast.card.noVoice': 'No voice',
  'cast.card.inVideos': 'In {n} videos',
  'cast.card.inVideo': 'In 1 video',
  'cast.dir.lead': 'Your studio’s cast: one image and one voice each, across every production.',
  'cast.dir.first': 'Start your first character',
  'cast.dir.filterIdentity': 'Identity',
  'cast.start.describe': 'Describe them',
  'cast.start.describe.hint': 'A line is enough; Casting does the rest.',
  'cast.start.sheet': 'Write the sheet',
  'cast.start.sheet.hint': 'You fill it in; the image is drawn when you ask.',
  'cast.start.picture': 'From a picture',
  'cast.start.picture.hint': 'The studio draws them to match your reference.',
  'cast.new.title': 'New character',
  'cast.new.lead': 'Start the way that suits you. Nothing is drawn until you say so.',
  'cast.new.how': 'How do you want to start?',
  'cast.new.for': 'For {name}',
  'cast.new.forLibrary': 'For the library',
  'cast.new.forLabel': 'Who it is for',
  'cast.new.change': 'Change',
  'cast.new.moreControl': 'More control',
  'cast.new.woman': 'Woman',
  'cast.new.man': 'Man',
  'cast.new.estimate': 'About a minute: the sheet, then the image.',
  'cast.new.imageLands': 'The image is drawn here',
  'cast.new.leaveSafe': 'You can leave this page: the work goes on, and the character’s profile shows it when it is done.',
  'cast.new.openProfile': 'Open the profile',
  'cast.sheet.steps': 'The sheet, in three steps',
  'cast.sheet.identity': 'Identity',
  'cast.sheet.look': 'Look',
  'cast.sheet.voice': 'Voice',
  'cast.sheet.step': 'Step',
  'cast.sheet.describeLook': 'Describe how they look',
  'cast.sheet.describeLookHelp': 'Build, face, hair, clothes, anything that marks them. Casting fills in what you leave out.',
  'cast.sheet.lookDetails': 'Details, field by field',
  'cast.sheet.performance': 'Performance notes',
  'cast.sheet.createHint': 'Create keeps the sheet; Create and draw also draws the image.',
  'cast.picture.drop': 'Drop a picture here',
  'cast.picture.browse': 'or choose one',
  'cast.picture.rules': 'PNG, JPEG or WebP · at least 512 px on the short side · up to 20 MB',
  'cast.picture.change': 'What should change?',
  'cast.step.design': 'Writing the sheet',
  'cast.step.image': 'Drawing the image',
  'cast.step.voice': 'Building the voice',
  'cast.step.approval': 'Awaiting your approval',
  'cast.step.thenApproval': 'Then the image waits for your approval.',
  'cast.ready.review': 'Review and approve',
  'cast.ready.approveHint': 'The image is a draft until you approve it on the profile.',
  'cast.ready.openHint': 'The character is ready.',
  'cast.ready.discard': 'Discard',
  'cast.created.approve': 'Review the image and approve it: it becomes the character’s identity everywhere.',
  'cast.created.noImage': 'The image was not drawn; draw it from here.',
  'cast.created.done': 'The character is ready.',
  'cast.created.noVoice': 'No voice yet: add a recording under Voice.',
  'cast.prod.title': 'Productions',
  'cast.prod.none': 'Not in any video yet.',
  'cast.prod.unknown': 'No video history on record.',
  'cast.prod.cast': 'Cast, not filmed yet',
  'cast.prod.imageVersion': 'image version',
  'cast.prod.versionUnknown': 'image version not recorded',
  'cast.secondary.title': 'Secondary material',
  'cast.secondary.lead': 'Optional pictures made on request. They never replace the character’s image.',
  'cast.secondary.portrait': 'Close-up portrait',
  'cast.secondary.expressions': 'Expressions',
  'cast.secondary.outfits': 'Outfits',
  'cast.secondary.earlier': 'Earlier views',
  'cast.secondary.none': 'None yet.',
  'cast.secondary.drawExpressions': 'Draw expressions',
  'cast.secondary.drawOutfit': 'Draw an outfit',
  'cast.voice.title': 'Voice identity',
  'cast.voice.of': 'the voice of',
  'cast.voice.src.recording': 'Recording',
  'cast.voice.src.generated': 'Generated',
  'cast.voice.src.sample': 'Sample',
  'cast.voice.noWave': 'The waveform could not be read from this file.',
  'cast.voice.previewLine': 'Preview a line',
  'cast.voice.speak': 'Speak it',
  'cast.voice.checkDetails': 'Check details',
  'cast.voice.empty': 'No voice yet. Choose how to make it below: automatically from the profile, by describing it, or from a recording.',
  'cast.voice.emptyIraqi': 'No voice yet. Iraqi voices are cloned from a real Iraqi recording: record or upload 5–12 seconds of the voice.',
  'cast.voice.locked': 'This character has spoken in a video, so the voice is kept as it is. You can still listen and preview lines.',
  'cast.voice.create': 'Create the voice',
  'cast.voice.replace': 'Replace the voice',
  'cast.voice.how': 'How the voice is made',
  'cast.voice.m.recording': 'Your recording',
  'cast.voice.m.recording.hint': 'Record here or drop a file; the voice is cloned from it.',
  'cast.voice.record': 'Record',
  'cast.voice.stop': 'Stop',
  'cast.voice.micRefused': 'The browser did not allow the microphone.',
  'cast.voice.drop': 'or drop a recording',
  'cast.voice.dropHint': 'WAV, MP3, M4A, OGG · 3–30 seconds',
  'cast.voice.measured': 'Measured',
  'cast.voice.clearSpeech': 'speech heard',
  'cast.voice.noSpeech': 'no speech heard',
  'cast.voice.reference': 'Reference',
  'cast.voice.useAsReference': 'Use as reference',
  'cast.voice.buildFrom': 'Build voice from',
  'cast.voice.takes': 'Takes',
  'cast.voice.takesHint': 'Lines spoken to try the voice. Listen only: a voice is never built from them.',
  'cast.voice.traits': 'How it should sound',
  'cast.voice.state.measured': 'Intelligible (measured)',
  'cast.voice.generatedLine': 'Generated line',
  'cast.voice.origin.designed': 'Studio-designed synthetic voice — not a real person',
  'cast.voice.origin.recording': 'Recording',
  'cast.voice.measuredLabel': 'Measured',
  'cast.voice.notMeasured': 'not measured yet',
  'cast.voice.intelligible': 'intelligible',
  'cast.voice.wordsHeard': '{p} of words heard',
  'cast.voice.loudnessOk': 'loudness OK',
  'cast.voice.loudnessOff': 'loudness outside the range',
  'cast.voice.listenedLabel': 'Listened',
  'cast.voice.notListened': 'nobody has listened yet — naturalness is not claimed',
  'cast.voice.natural': 'natural {n} of 5',
  'cast.voice.iraqiYes': 'sounds authentically Iraqi',
  'cast.voice.iraqiNo': 'does not sound Iraqi',
  'cast.voice.iListened': 'I listened',
  'cast.voice.naturalQ': 'How natural does it sound?',
  'cast.voice.naturalHelp': '1 = clearly synthetic, 5 = could be a person.',
  'cast.voice.iraqiQ': 'Does it sound authentically Iraqi?',
  'cast.voice.yes': 'Yes',
  'cast.voice.no': 'No',
  'cast.voice.listenNote': 'Note',
  'cast.voice.saveListening': 'Save what I heard',
  'cast.voice.listenSaved': 'Listening recorded',
  'cast.voice.accentPending': 'The Arabic accent has not been verified by a listener yet.',
  'cast.voice.iraqiPending': 'The Iraqi dialect has not been verified by a listener yet.',
  'cast.voice.m.automatic': 'Automatic',
  'cast.voice.m.automatic.hint': 'One action: the studio makes the voice from the profile.',
  'cast.voice.m.design': 'Design a voice',
  'cast.voice.m.design.hint': 'Describe it, hear three candidates, choose one.',
  'cast.voice.iraqiNeedsRecording': 'Iraqi voices are cloned from a real Iraqi recording — record or upload 5–12 seconds of the voice.',
  'cast.voice.auto.en': 'A synthetic voice is designed from the profile (sex, age, pitch, pace, timbre), measured, and the best of three is pinned.',
  'cast.voice.auto.msa': 'A synthetic Modern Standard Arabic voice is designed from the profile, measured, and the best of three is pinned. Its accent waits for a listener.',
  'cast.voice.auto.iraqiFromRecording': 'The voice is cloned from your Iraqi recording.',
  'cast.voice.auto.iraqiExperiment': 'Experiment on: a designed Arabic voice is used for an Iraqi character; the dialect stays unverified until a listener confirms it.',
  'cast.voice.auto.go': 'Make the voice',
  'cast.voice.design.description': 'Describe the voice',
  'cast.voice.design.help': 'Written from the profile; change anything. Never name or imitate a real person.',
  'cast.voice.design.iraqiNote': 'Designed voices speak English or Modern Standard Arabic; an Iraqi voice needs a recording.',
  'cast.voice.design.go': 'Design three voices',
  'cast.voice.design.candidates': 'Candidates',
  'cast.voice.design.candidate': 'Candidate',
  'cast.voice.design.choose': 'Choose this voice',
  'cast.voice.design.failedGate': 'did not pass the measured gates',
  'cast.voice.consent': 'Whose voice is this?',
  'cast.voice.consent.mine': 'This is my voice',
  'cast.voice.consent.permission': 'I have the speaker’s permission',
  'cast.voice.consent.recorded': 'Your statement is recorded with the recording.',
  'cast.voice.consentFirst': 'Say whose voice it is before recording or uploading.',
  'cast.voice.consentFor': '“{label}” has no consent statement. Whose voice is it?',
  'cast.voice.consentAndRetry': 'Confirm and try again',
  // ---- end of characters v3 block ----
  // voice tab
  'voice.engine.habibi': 'Iraqi dialect engine',
  'voice.engine.indextts': 'Bilingual studio engine',
  'voice.engine.minimax': 'MiniMax clone', // v4-lint: allow engine — pre-existing copy that names an engine; the page package that rewrites this page writes it engine-free (character voice)
  'voice.revision': 'revision',
  'voice.identity.review': 'Needs a listen',
  'voice.identity.stale': 'Out of date: the language changed',
  'voice.identity.unchecked': 'Not checked',
  'voice.identity.noProof': 'No proof line was kept for this voice.',
  'voice.identity.heard': 'Heard',
  'voice.identity.coverage': 'Coverage',
  'voice.identity.cer': 'Character error rate',
  'voice.identity.wer': 'Word error rate',
  'voice.identity.none': 'No voice yet',
  'voice.identity.notBuiltYet': 'Chosen as the reference. Build the voice to make it the one the character speaks with.',
  'voice.identity.sampleChosen': 'A sample line, to listen to. The studio never builds a voice from a sample or a generated line: upload a recording.',
  'voice.recordings': 'Your recordings',
  'voice.noRecordings': 'No recording yet.',
  'voice.measured.ok': 'length ok',
  'voice.measured.long': 'over 30 s',
  'voice.measured.longHint': 'A window of up to 12 seconds after a short lead-in is used.',
  'voice.measured.unknown': 'length could not be read here; the studio measures it',
  'voice.checkedByStudio': 'Checked by the studio',
  'voice.langUnknown': 'language unclear',
  'voice.refuse.TOO_SHORT': 'Too short: at least 3 seconds of speech.',
  'voice.refuse.TOO_LONG': 'Too long: 30 seconds at most.',
  'voice.refuse.NO_SPEECH': 'No speech was heard: at least three words.',
  'voice.refuse.TOO_QUIET': 'Too quiet to use.',
  'voice.refuse.CLIPPING': 'The recording clips (distorted peaks).',
  'voice.refuse.WRONG_LANGUAGE': 'This recording is in another language than the character speaks.',
  'voice.refuse.BAD_FORMAT': 'The file could not be read as audio.',
  'voice.build.needRecording': 'Upload a recording first.',
  'voice.dialectEngine': 'The language and dialect choose the engine; Latin words in an Arabic line go to the bilingual engine.',
  // ---- studio --------------------------------------------------------------------------------------------------------
  'settings.startEmpty': 'Start with an empty studio',
  'settings.startEmpty.hint': 'Removes every show, character, location and file on this server. Your settings stay.',
  'settings.startEmptyConfirm': 'Remove everything and start with an empty studio?',
  'settings.data.empty': 'The studio is empty.',

  // settings
  'settings.interface': 'Interface',
  'settings.defaults': 'Defaults for new projects',
  'settings.data': 'Studio data',
  'settings.data.hint': 'Everything you make is saved in the studio database and the library on this server.',
  'settings.data.holds': 'This studio holds {productions} productions, {characters} characters, {locations} locations and {files} files.',
  'settings.data.began.empty': 'Started as an empty studio on {date}.',
  'settings.data.began.sample': 'Loaded from the test sample on {date} (a test run).',
  'settings.about': 'About this studio',
  'settings.about.body': 'Vewbox Studio runs on this server: writing by the story engine, pictures and voices on the local GPU, video by MiniMax (hosted or local), assembly and export by ffmpeg. The database is the record; every generated file carries its provenance.', // v4-lint: allow engine — pre-existing copy that names an engine; the page package that rewrites this page writes it engine-free (Settings)
  'settings.motion': 'Reduce motion',
  'settings.motion.hint': 'Turns off transitions and animations in the interface.',
  'settings.lead': 'The interface, the defaults for new projects, the engines and models behind this studio, and its data.',
  'settings.generation.body': 'The hosted MiniMax API is not configured on this server: add MINIMAX_API_KEY to the server’s .env to generate video with it. Video can also come from the local MiniMax H3 engine when ComfyUI reports it above. Nothing is simulated: a button whose engine is not running says so and the job fails with the reason.', // v4-lint: allow engine — pre-existing copy that names an engine; the page package that rewrites this page writes it engine-free (Settings)
  'asset.protected': 'This picture is part of the appearance of a character who has been in a video, so it is kept:',
  'jobs.title': 'Activity',
  'jobs.lead': 'Everything the studio is doing or has done: writing, drawing, generating, assembling. Cancel, retry or open the result from here.',
  'jobs.empty': 'Nothing has run yet.',
  'jobs.empty.hint': 'Start a production step — write the script, draw a character, generate a take — and it appears here.',
  'jobs.active': 'Running',
  'jobs.queued': 'Queued',
  'jobs.done': 'Finished',
  'jobs.failed': 'Failed',
  'jobs.cancelled': 'Cancelled',
  'jobs.awaitingReview': 'Awaiting review',
  'jobs.attempt': 'attempt',
  'jobs.cancel': 'Cancel',
  'jobs.retry': 'Retry',
  'jobs.details': 'Details',
  'jobs.events': 'Log',
  'jobs.result': 'Result',
  'jobs.error': 'Error',
  'jobs.open': 'Open',
  'jobs.filter.all': 'All',
  'jobs.filter.active': 'Active',
  'jobs.filter.failed': 'Failed',
  'jobs.queue': 'Queue',
  'jobs.running': 'running',
  'jobs.waiting': 'waiting',
  'jobs.provider': 'Provider task',
  'jobs.started': 'Started',
  'jobs.finished': 'Finished',
  'jobs.cancelRequested': 'Stopping…',
  'jobs.inProgress': 'In progress',
  'registry.title': 'Models',
  'registry.lead': 'Every pinned weight and hosted model the studio can use, with its licence and whether its engine can see it right now.',
  'registry.showAll': 'Show all',
  'registry.showFewer': 'Show fewer',
  'registry.workflows': 'Workflow versions',
  'registry.status.PRESENT': 'Present',
  'registry.status.MISSING': 'Not downloaded',
  'registry.status.CONFIGURED': 'Key set',
  'registry.status.NO_KEY': 'No key',
  'registry.status.SERVICE': 'Service',
  'registry.status.UNKNOWN': 'Unknown',
  'reliability.title': 'Reliability',
  'reliability.lead': 'Job outcomes and timings over the last seven days, as recorded by the worker.',
  'reliability.none': 'No jobs have run yet.',
  'reliability.completed': 'completed',
  'reliability.failed': 'failed',
  'reliability.cancelled': 'cancelled',
  'reliability.running': 'running',
  'reliability.attempts': 'attempts',
  'reliability.timings': 'Timings',
  'studio.director': 'Director',
  'studio.activity.empty': 'No activity recorded yet. Start a production and the departments appear here as they work.',
  'studio.pipeline': 'How a production moves',
  'studio.reliability': 'Reliability',
  'studio.reliability.hint': 'From the recorded runs, inspections and retries of the last seven days.',
  'studio.firstAttempt': 'First-attempt success',
  'studio.firstAcceptance': 'First-attempt acceptance',
  'studio.retryRate': 'Retry rate',
  'studio.qaRejections': 'QA rejections',
  'studio.exportSuccess': 'Export success',
  'studio.perAccepted': 'Per accepted shot',
  'studio.failureClasses': 'Failure classes',
  'studio.noFailures': 'No failures recorded.',
  'studio.skills': 'Skills',
  'studio.tools': 'Tools',
  'studio.instructions': 'Instructions',
  'studio.quality': 'Quality requirements',
  'studio.advisory': 'Owns no job type of its own: it works as delegated steps inside other agents’ jobs, each recorded as its own run.',
  'studio.instructionsModel': 'Instructions (sent with every model call it makes)',
  'studio.instructionsDoc': 'Rules its code applies (documentation; reaches no model)',
  'studio.skillUnavailable': 'Unavailable on this machine',
  'studio.skillValidated': 'Verified: implementation and tests present',
  'studio.skillDraft': 'Draft',
  'studio.recentRuns': 'Recent runs',
  'orch.title': 'Studio Orchestrator',
  'orch.diagram': 'The company: the orchestrator and the departments',
  'orch.state.IDLE': 'Idle',
  'orch.state.READY': 'Ready',
  'orch.state.COORDINATING': 'Coordinating',
  'orch.state.PRODUCING': 'Producing',
  'orch.state.AWAITING_REVIEW': 'Awaiting review',
  'orch.state.BLOCKED': 'Blocked',
  'orch.stateHint.IDLE': 'no production in progress',
  'orch.stateHint.READY': 'productions in progress, nothing running right now',
  'orch.stateHint.COORDINATING': 'planning, writing or orchestration is running',
  'orch.stateHint.PRODUCING': 'the GPU is generating pictures, voices or video',
  'orch.stateHint.AWAITING_REVIEW': 'a decision is waiting for you',
  'orch.stateHint.BLOCKED': 'a handoff was refused or a stage was rejected',
  'orch.node.idle': 'Idle',
  'orch.node.active': 'Working',
  'orch.blocked': 'Blocked',
  'orch.accepted': 'Accepted',
  'orch.refused': 'Refused',
  'studio.failureHistory': 'Failure history',
  'studio.noFailureHistory': 'No failures recorded for this agent.',
  // counted phrases: `one|other` (T.p); {n} is the count
  'co.lead': 'Who is working on what, and every handoff between the departments.',
  'co.viewList': 'View as list',
  'co.inspector': 'Selection',
  'co.stageHint': 'Use the arrow keys to move around the company, Enter to select a department and Enter again to open it, Escape to return to the orchestrator.',
  'co.empty.caption': 'No handoffs yet. Each handoff between departments lights its path.',
  'co.lastKnown': 'Last known · {ago}',
  'co.legend': 'What the lines mean',
  'co.legend.used': 'Used path',
  'co.legend.recent': 'Handed off in the last 90 min',
  'co.legend.waiting': 'Waiting for you',
  'co.legend.refused': 'Refused',
  'co.agents': '1 agent|{n} agents',
  'co.node.working': 'Working · {agent}',
  'co.node.waiting': 'Waiting for you',
  'co.handoffsRecent': '1 handoff in the last 90 minutes|{n} handoffs in the last 90 minutes',
  'co.noRecentHandoffs': 'No handoffs in the last 90 minutes',
  'co.orch.coordinating': 'Coordinating 1 production|Coordinating {n} productions',
  'co.orch.inProgress': '1 production in progress|{n} productions in progress',
  'co.orch.waiting': 'Waiting for you · {n}',
  'co.orch.blocked': 'Blocked · {n}',
  'co.orch.more': '+{n} more',
  'co.orch.sentence.idle': 'Idle — nothing in production.',
  'co.waitingForYou': 'Waiting for you',
  'co.inProduction': 'In production',
  'co.recentDecisions': 'Recent decisions',
  'co.how.title': 'How the company works',
  'co.how.1': 'Story Development writes it; Casting and World Building give it faces and places; Pre-Production plans the shots.',
  'co.how.2': 'Sound & Music records the voices and songs, Video Production films each shot, and Quality Assurance checks every take.',
  'co.how.3': 'Post-Production cuts and exports. You approve the story before filming and the cut before export.',
  'co.startProduction': 'Start a production',
  'co.addCharacter': 'Add a character',
  'co.failedJobs': '1 failed job|{n} failed jobs',
  'co.dept.eyebrow': 'Department',
  'co.team': 'Team',
  'co.receivesFrom': 'Receives from',
  'co.handsTo': 'Hands to',
  'co.afterApproval': 'after your approval',
  'co.coordinates': 'Coordinates every stage and holds your approval gates.',
  'co.fromYou': 'Starts from your brief.',
  'co.toYou': 'Delivers the finished film to you.',
  'co.edge.none': 'No handoff yet',
  'co.edge.used': 'Last handoff {ago}',
  'co.edge.recent': 'Handed off {ago}',
  'co.edge.waiting': 'Waiting for your approval',
  'co.edge.refused': 'Last handoff refused',
  'co.edge.eyebrow': 'Handoff path',
  'co.carries': 'Carries',
  'co.lastHandoffs': 'Last handoffs',
  'co.checksPassed': '{ok} of {n} checks passed',
  'co.openProduction': 'Open production',
  'co.currentWork': 'Current work',
  'co.nothingAssigned': 'Nothing assigned.',
  'co.openDept': 'Open department',
  'co.recentHandoffs': 'Recent handoffs',
  'co.recentHandoffs.empty': 'No handoffs yet. They appear here as the departments pass work on.',
  'co.spine.title': 'Departments, in production order',
  'co.announce': '{from} handed {stage} to {to}',
  'co.error': 'The studio server did not answer.',
  'co.tryAgain': 'Try again',
  'co.running': 'Running',
  'co.lastRun': 'Last ran {ago}',
  'co.neverRun': 'Never run',
  'rel.measure': 'Measure',
  'rel.value': 'Value',
  'rel.from': 'From',
  'rel.ofRuns': '{a} of {b} first runs',
  'rel.ofTakes': '{a} of {b} first takes',
  'rel.ofJobs': '{a} of {b} jobs',
  'rel.ofReports': '{a} of {b} reports',
  'rel.ofExports': '{a} of {b} exports',
  'rel.inReview': '{n} in review',
  'rel.acceptedTakes': '1 accepted take|{n} accepted takes',
  'rel.attemptsEach': '{x} attempts each',
  'rel.resolved': '{n} resolved',
  'fail.INVALID_INPUT': 'Invalid input',
  'fail.UNSUPPORTED_CAPABILITY': 'Not supported by the engine',
  'fail.MISSING_REFERENCE': 'Missing reference',
  'fail.INCONSISTENT_PLAN': 'Inconsistent plan',
  'fail.PROMPT_AMBIGUITY': 'Ambiguous prompt',
  'fail.WRONG_PARAMETERS': 'Wrong parameters',
  'fail.INFRASTRUCTURE': 'Infrastructure',
  'fail.PROVIDER': 'Engine or provider error',
  'fail.RESOURCE_EXHAUSTION': 'Out of resources',
  'fail.CHARACTER_INCONSISTENCY': 'Character drift',
  'fail.ENVIRONMENT_INCONSISTENCY': 'Environment drift',
  'fail.VOICE_MISMATCH': 'Voice mismatch',
  'fail.LIP_SYNC_FAILURE': 'Lip-sync failure',
  'fail.AUDIO_DUPLICATION': 'Doubled audio',
  'fail.OUTPUT_CORRUPTION': 'Corrupt output',
  'fail.CANCELLED': 'Cancelled',
  'fail.UNKNOWN': 'Unknown cause',
  'dept.showInCompany': 'Show in company',
  'dept.place': 'Place in the pipeline',
  'dept.executes': 'Executes',
  'dept.steps': 'Delegated steps',
  'dept.noPath': 'No execution path recorded',
  'dept.work': 'Work',
  'dept.work.now': 'Now',
  'dept.work.delivered': 'Delivered',
  'dept.work.quality': 'Quality',
  'dept.work.activity': 'Activity',
  'dept.empty.now': 'Nothing assigned right now. Work arrives here when a production reaches this department.',
  'dept.empty.delivered': 'Nothing handed off yet.',
  'dept.empty.quality': 'No inspection recorded yet.',
  'dept.openProduction': 'Open Production',
  'dept.planned': 'Not yet staffed',
  'dept.planned.hint': 'Roles this department will have. No code runs them yet, so they have no profile, tools or activity.',
  'dept.planned.phase': 'When: {phase}',
  'dept.how': 'How this department works',
  'dept.models': 'Models',
  'dept.technical': 'Technical details',
  'dept.contract.input': 'Takes',
  'dept.contract.output': 'Returns',
  'dept.contract.none': 'No contract recorded.',
  'dept.contract.noFields': 'No named fields.',
  'dept.required': 'required',
  'dept.optional': 'optional',
  'dept.toolMeta': 'Version {v} · {res} · up to {min} min',
  'dept.permissions': 'Touches',
  'dept.errors': 'Can fail with',
  'dept.runs': '1 run|{n} runs',
  'dept.firstTime': '{p} first time',
  'dept.median': 'median {t}',
  'dept.failures': '1 failure|{n} failures',
  'skill.kind.PROMPT': 'Read by the model',
  'skill.kind.PROCEDURE': 'Carried out by code',
  'skill.kind.REFERENCE': 'Reference only, never run',
  'skill.implementedBy': 'Implemented in',
  'skill.verifiedBy': 'Checked by',
  'skill.injectedInto': 'Sent to',
  'skill.missing': 'missing',
  'skill.version': 'Version {v}',
  'agent.now': 'Now',
  'agent.track': 'Track record',
  'agent.noRuns': 'No runs yet.',
  'agent.delegated': 'Delegated step',
  'agent.whenRoute': 'when {when}',
  'agent.modelLimits': 'Model and limits',
  'agent.attempts': '1 attempt|{n} attempts',
  'agent.limits': 'Up to {min} min a run · {attempts} · {res}',
  'agent.io': 'Input and output',
  'agent.stepsWhere': 'Where its delegated steps run',
  'agent.version': 'Version {v}',
  'agent.attemptN': 'attempt {n}',
  'agent.changeMade': 'Changed: {change}',
  'agent.const.APPEARANCE_LOCKED': 'the appearance lock',
  'agent.const.VOICE_LOCKED': 'the voice lock',
  'res.LLM': 'Language model',
  'res.GPU_IMAGE': 'GPU, pictures',
  'res.GPU_VIDEO': 'GPU, video',
  'res.TTS': 'Speech engine',
  'res.ASR': 'Transcription engine',
  'res.CPU': 'Processor',
  'res.HOSTED': 'Hosted service',
  'res.NONE': 'No engine',
  'studio.approve': 'Approve',
  'studio.requestChanges': 'Request changes',
  'studio.awaitingApproval': 'Awaiting your approval',
  'studio.stage.DONE': 'Done',
  'studio.stage.AWAITING_APPROVAL': 'Awaiting approval',
  'studio.stage.REJECTED': 'Rejected',
  'studio.stage.INVALID': 'Handoff refused',
  'studio.stage.READY': 'Ready',
  'studio.stage.BLOCKED': 'Waiting',
  'production.title': 'Production',
  'production.lead': 'Where each production stands in the pipeline, what is waiting for you, and everything the studio is running.',
  'production.empty': 'Nothing in production.',
  'production.empty.hint': 'Start a show, a short or a music video from Projects.',
  'screening.title': 'Screening Room',
  'screening.lead': 'Finished cuts and exports, ready to watch.',
  'screening.empty': 'Nothing to screen yet.',
  'screening.empty.hint': 'A production appears here once its cut is assembled.',
  'screening.cut': 'Assembled cut',
  'pipeline.STORY': 'Story',
  'pipeline.CAST_WORLD': 'Cast & world',
  'pipeline.SCRIPT': 'Script',
  'pipeline.STORYBOARD': 'Storyboard',
  'pipeline.SHOT_PLAN': 'Shot plan',
  'pipeline.AUDIO_PREP': 'Audio preparation',
  'pipeline.VIDEO': 'Video generation',
  'pipeline.QA': 'Quality assurance',
  'pipeline.EDIT': 'Edit',
  'pipeline.EXPORT': 'Export',
  'production.decisions': 'Needs your decision',
  'production.decisions.hint': 'Stages waiting for your approval before the studio goes on.',
  'production.decisions.none': 'Nothing waits for you right now.',
} as const;

export type Key = keyof typeof COPY;
export const KEYS = Object.keys(COPY) as Key[];

const fill = (s: string, vars: Record<string, string | number>) => s.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
/** A counted phrase is `one|other`; a string without `|` is used for every count. */
const plural = (s: string, n: number) => { const i = s.indexOf('|'); return i < 0 ? s : n === 1 ? s.slice(0, i) : s.slice(i + 1); };
/** An unknown dynamic key becomes readable words: `stage.FINAL_CUT` → "Final cut". */
const words = (key: string) => key.split('.').pop()!.replace(/_/g, ' ').toLowerCase().replace(/^./, (c) => c.toUpperCase());

/** The English string of a key. */
export const T = Object.assign((key: Key): string => COPY[key], {
  dyn: (key: string, fallback?: string): string => (COPY as Record<string, string>)[key] ?? fallback ?? words(key),
  f: (key: Key, vars: Record<string, string | number>): string => fill(COPY[key], vars),
  p: (key: Key, n: number, vars: Record<string, string | number> = {}): string => fill(plural(COPY[key], n), { n, ...vars }),
});
export type TFn = typeof T;
