/** IMAGE PRESENTATION — the shared contract of docs/DESIGN-SYSTEM-V4.md §2.4.
 *
 *  Computed once by the server when an image asset is ingested (package B1: src/server/media/presentation.ts) and
 *  stored on the asset; read by the media components (package F3), which must render neutral when it is absent.
 *  Nothing here is generated by a model: every field is measured from the pixels or set by the producer. */

/** Measured facts about one image, all optional. */
export interface Presentation {
  /** 'oklch(L C H)', unclamped: the heaviest chroma-weighted hue bucket; absent for grey studio backdrops. */
  dominant?: string;
  /** Mean colour of a 4 px border ring: the letterbox fill and the figure-frame field. */
  edge?: string;
  /** The edge's luminance is above 0.8. */
  lightBackdrop?: boolean;
  /** 0–1 point the crops keep in view; default { x: 0.5, y: 0.4 }. */
  focal?: { x: number; y: number };
  /** 0–1 face box, figures only. */
  faceBox?: { x: number; y: number; w: number; h: number };
  /** 0–1 point a PORTRAIT (2:3) crop keeps in view when it differs from `focal` (the frame poster, a 2:3 tile cut
   *  from a wide frame); set by the producer or the poster step, never measured. Absent: `focal`, then DEFAULT_FOCAL. */
  portraitFocal?: { x: number; y: number };
}

/** The CSS custom properties a lobby hero or tile receives (B1's `artVars`); absent keys mean neutral. */
export type ArtVars = Partial<Record<'--art' | '--art-ph' | '--art-edge', string>>;

/** The focal point every crop uses when an image has none. */
export const DEFAULT_FOCAL = { x: 0.5, y: 0.4 } as const;
