import type { JobType } from '@/domain/jobs';

/** THE STUDIO ORGANISATION — the company as code. Departments own stages of filmmaking; agents are the registered
 *  identities that execute work inside a department with a job description, the model that actually runs for them,
 *  the skills they read and the tools they are allowed to call. The worker executes every job *as* one of these
 *  agents and records the run. This file is the source of truth; `registry.ts` persists it (with versions) so the
 *  Studio pages, the API and the history all read the same organisation. Nothing here is decorative: an agent that
 *  owns no job type and no tool does not appear in the live activity, and the pages say so. */

export const ORG_VERSION = 2;

export type DepartmentId = 'EXECUTIVE' | 'STORY' | 'CASTING' | 'WORLD' | 'PREPRODUCTION' | 'VIDEO' | 'SOUND' | 'POST' | 'QA';

export type ResourceFamily = 'LLM' | 'GPU_IMAGE' | 'GPU_VIDEO' | 'TTS' | 'ASR' | 'CPU' | 'HOSTED' | 'NONE';

export interface ToolDef {
  id: string;
  name: string;
  description: string;
  version: string;
  /** which registered schema validates input and output (see tools.ts) */
  inputSchema: string;
  outputSchema: string;
  permissions: string[];
  timeoutMs: number;
  resource: ResourceFamily;
  /** VRAM the lease reserves for a GPU family, MB */
  vramMb?: number;
  /** failure classes this tool can raise */
  errors: string[];
}

export interface SkillDef {
  id: string;
  name: string;
  /** folder under skills/ with SKILL.md (Anthropic Agent Skills format) */
  path: string;
  source: string;
  sourceVersion: string;
  supportedModels: string[];
  requiredTools: string[];
  /** VALIDATED: read and exercised in this studio; UNAVAILABLE: needs something this machine lacks (a key); DRAFT */
  status: 'VALIDATED' | 'UNAVAILABLE' | 'DRAFT';
  note?: string;
}

export interface AgentDef {
  id: string;
  name: string;
  department: DepartmentId;
  role: string;
  description: string;
  systemInstructions: string;
  /** the model that actually runs when this agent works */
  model: string;
  skills: string[];
  tools: string[];
  inputSchema: string;
  outputSchema: string;
  limits: { timeoutMs: number; maxAttempts: number; resource: ResourceFamily };
  version: string;
  qualityRequirements: string[];
  /** job types this agent executes; empty for supervisory and advisory agents whose work is recorded as events */
  jobTypes: JobType[];
}

export interface DepartmentDef {
  id: DepartmentId;
  name: string;
  nameAr: string;
  directorId: string;
  responsibility: string;
  stages: PipelineStage[];
  order: number;
}

export type PipelineStage = 'STORY' | 'CAST_WORLD' | 'SCRIPT' | 'STORYBOARD' | 'SHOT_PLAN' | 'AUDIO_PREP' | 'VIDEO' | 'QA' | 'EDIT' | 'EXPORT';

export interface StageDef { id: PipelineStage; name: string; department: DepartmentId; dependsOn: PipelineStage[]; jobTypes: JobType[]; /** the department that receives the handoff */ handsTo?: DepartmentId; approval?: 'HUMAN' }

export const PIPELINE: StageDef[] = [
  { id: 'STORY', name: 'Story', department: 'STORY', dependsOn: [], jobTypes: ['AUTO_IDEA', 'DEVELOP_STORY'], handsTo: 'CASTING', approval: 'HUMAN' },
  { id: 'CAST_WORLD', name: 'Cast & world', department: 'CASTING', dependsOn: ['STORY'], jobTypes: ['DESIGN_CHARACTER', 'CHARACTER_APPEARANCE', 'CHARACTER_REFS', 'VOICE_BUILD', 'LOCATION_PLATES'], handsTo: 'STORY' },
  { id: 'SCRIPT', name: 'Script', department: 'STORY', dependsOn: ['STORY'], jobTypes: ['WRITE_SCRIPT'], handsTo: 'PREPRODUCTION' },
  { id: 'STORYBOARD', name: 'Storyboard', department: 'PREPRODUCTION', dependsOn: ['SCRIPT', 'CAST_WORLD'], jobTypes: ['SHOT_FRAMES'], handsTo: 'PREPRODUCTION' },
  { id: 'SHOT_PLAN', name: 'Shot plan', department: 'PREPRODUCTION', dependsOn: ['SCRIPT'], jobTypes: ['PLAN_SHOTS'], handsTo: 'SOUND' },
  { id: 'AUDIO_PREP', name: 'Audio preparation', department: 'SOUND', dependsOn: ['SHOT_PLAN', 'CAST_WORLD'], jobTypes: ['GENERATE_SONG', 'DIALOGUE_AUDIO', 'VOICE_PREVIEW'], handsTo: 'VIDEO' },
  // PRODUCE is the Production Coordinator's orchestration across stages, not a stage job
  { id: 'VIDEO', name: 'Video generation', department: 'VIDEO', dependsOn: ['SHOT_PLAN', 'STORYBOARD', 'AUDIO_PREP'], jobTypes: ['GENERATE_TAKE'], handsTo: 'QA' },
  { id: 'QA', name: 'Quality assurance', department: 'QA', dependsOn: ['VIDEO'], jobTypes: [], handsTo: 'POST' },
  { id: 'EDIT', name: 'Edit', department: 'POST', dependsOn: ['QA'], jobTypes: ['ASSEMBLE'], handsTo: 'POST', approval: 'HUMAN' },
  { id: 'EXPORT', name: 'Export', department: 'POST', dependsOn: ['EDIT'], jobTypes: ['EXPORT'] },
];

// ---------------------------------------------------------------------------------------------------------- tools

export const TOOLS: ToolDef[] = [
  { id: 'story.structured_answer', name: 'Structured story answer', description: 'Ask the story model for one JSON object against a schema, with lenient repair rounds; returns validated data and the model’s usage.', version: '1.2.0', inputSchema: 'StructuredAnswerInput', outputSchema: 'StructuredAnswerOutput', permissions: ['llm'], timeoutMs: 180_000, resource: 'LLM', errors: ['PROVIDER', 'INVALID', 'UNAVAILABLE'] },
  { id: 'image.generate', name: 'Generate a picture', description: 'Qwen-Image-2512 text-to-image in ComfyUI (Lightning, 8 steps).', version: '1.1.0', inputSchema: 'ImageGenerateInput', outputSchema: 'ImageOutput', permissions: ['gpu'], timeoutMs: 1_200_000, resource: 'GPU_IMAGE', vramMb: 20000, errors: ['PROVIDER', 'UNAVAILABLE'] },
  { id: 'image.edit_with_references', name: 'Draw from references', description: 'Qwen-Image-Edit-2511 with up to three reference pictures (identity, plate), in ComfyUI.', version: '1.1.0', inputSchema: 'ImageEditInput', outputSchema: 'ImageOutput', permissions: ['gpu'], timeoutMs: 1_200_000, resource: 'GPU_IMAGE', vramMb: 20000, errors: ['PROVIDER', 'UNAVAILABLE'] },
  { id: 'video.minimax_generate', name: 'Generate a MiniMax H3 clip', description: 'MiniMax H3 (the only video engine): first/last-frame or reference-to-video with pictures, audio and guides; local ComfyUI graphs or the hosted API when a key exists. Native stereo audio.', version: '2.0.0', inputSchema: 'VideoGenerateInput', outputSchema: 'VideoOutput', permissions: ['gpu', 'minimax'], timeoutMs: 5_400_000, resource: 'GPU_VIDEO', vramMb: 28000, errors: ['PROVIDER', 'UNAVAILABLE', 'NOT_CONFIGURED', 'INVALID'] },
  { id: 'speech.synthesize', name: 'Speak a line', description: 'IndexTTS 2.5 (English, Arabic, mixed) or Habibi-TTS IRQ (Iraqi Arabic) from a reference recording; MiniMax speech when a key exists.', version: '1.2.0', inputSchema: 'SynthesizeInput', outputSchema: 'SynthesizeOutput', permissions: ['gpu', 'minimax'], timeoutMs: 600_000, resource: 'TTS', vramMb: 8000, errors: ['PROVIDER', 'UNAVAILABLE', 'NOT_CONFIGURED'] },
  { id: 'speech.clone_voice', name: 'Clone a voice (hosted)', description: 'MiniMax voice cloning from a reference recording; needs a MiniMax API key.', version: '1.0.0', inputSchema: 'CloneVoiceInput', outputSchema: 'CloneVoiceOutput', permissions: ['minimax'], timeoutMs: 600_000, resource: 'HOSTED', errors: ['PROVIDER', 'NOT_CONFIGURED'] },
  { id: 'speech.transcribe', name: 'Transcribe', description: 'faster-whisper large-v3 with word timings.', version: '1.1.0', inputSchema: 'TranscribeInput', outputSchema: 'TranscribeOutput', permissions: ['gpu'], timeoutMs: 600_000, resource: 'ASR', vramMb: 4000, errors: ['PROVIDER', 'UNAVAILABLE'] },
  { id: 'audio.separate_stems', name: 'Separate stems', description: 'Demucs htdemucs: vocals and accompaniment.', version: '1.0.0', inputSchema: 'StemsInput', outputSchema: 'StemsOutput', permissions: ['gpu'], timeoutMs: 1_200_000, resource: 'ASR', vramMb: 4000, errors: ['PROVIDER', 'UNAVAILABLE'] },
  { id: 'music.generate', name: 'Compose a song', description: 'ACE-Step 1.5 XL turbo or MiniMax Music 3 in ComfyUI from a caption and lyrics (MiniMax Music API when a key exists).', version: '1.2.0', inputSchema: 'MusicInput', outputSchema: 'MusicOutput', permissions: ['gpu', 'minimax'], timeoutMs: 1_800_000, resource: 'GPU_IMAGE', vramMb: 14000, errors: ['PROVIDER', 'UNAVAILABLE', 'NOT_CONFIGURED'] },
  { id: 'media.probe', name: 'Probe a file', description: 'ffprobe: streams, durations, frame rate, size.', version: '1.0.0', inputSchema: 'FileInput', outputSchema: 'ProbeOutput', permissions: ['fs'], timeoutMs: 60_000, resource: 'CPU', errors: ['INVALID'] },
  { id: 'media.qa_take', name: 'Check a take', description: 'Decodability, duration, size, black and frozen frames, flicker, silence, true peak.', version: '1.1.0', inputSchema: 'QaTakeInput', outputSchema: 'QaReport', permissions: ['fs'], timeoutMs: 300_000, resource: 'CPU', errors: ['INVALID'] },
  { id: 'media.assemble', name: 'Assemble a cut', description: 'Frame-exact picture join, typed sample-placed mix plan, EBU R128 loudness, encode, subtitles.', version: '2.0.0', inputSchema: 'AssembleInput', outputSchema: 'AssembleOutput', permissions: ['fs'], timeoutMs: 3_600_000, resource: 'CPU', errors: ['INVALID', 'PROVIDER'] },
  { id: 'media.validate_export', name: 'Validate a finished file', description: 'Lengths within a frame, frame rate, size, timestamps, black stretches.', version: '1.0.0', inputSchema: 'ValidateExportInput', outputSchema: 'ExportValidation', permissions: ['fs'], timeoutMs: 600_000, resource: 'CPU', errors: ['INVALID'] },
  { id: 'media.align_lag', name: 'Measure sound-to-picture lag', description: 'Loudness-envelope cross-correlation of a take against the master stretch.', version: '1.0.0', inputSchema: 'AlignLagInput', outputSchema: 'AlignLagOutput', permissions: ['fs'], timeoutMs: 120_000, resource: 'CPU', errors: ['INVALID'] },
  { id: 'lyrics.align', name: 'Align lyrics to a vocal', description: 'Fuzzy monotone alignment of written lines to transcribed words.', version: '1.0.0', inputSchema: 'LyricsAlignInput', outputSchema: 'LyricsAlignOutput', permissions: [], timeoutMs: 60_000, resource: 'NONE', errors: [] },
  { id: 'studio.command', name: 'Studio command', description: 'A typed command of the command engine (records, continuity, selections) applied atomically with a new version.', version: '1.0.0', inputSchema: 'StudioCommandInput', outputSchema: 'StudioCommandOutput', permissions: ['studio:write'], timeoutMs: 30_000, resource: 'NONE', errors: ['INVALID', 'NOT_FOUND', 'APPEARANCE_LOCKED', 'CONFLICT'] },
  { id: 'studio.read', name: 'Studio snapshot', description: 'The authoritative studio state (or a part of it).', version: '1.0.0', inputSchema: 'StudioReadInput', outputSchema: 'StudioReadOutput', permissions: ['studio:read'], timeoutMs: 30_000, resource: 'NONE', errors: [] },
  { id: 'jobs.enqueue', name: 'Queue a job', description: 'A durable child job with an idempotency key.', version: '1.0.0', inputSchema: 'EnqueueInput', outputSchema: 'EnqueueOutput', permissions: ['jobs:write'], timeoutMs: 30_000, resource: 'NONE', errors: ['INVALID'] },
];

// --------------------------------------------------------------------------------------------------------- skills

export const SKILLS: SkillDef[] = [
  { id: 'h3-prompting', name: 'MiniMax H3 prompting', path: 'skills/h3-prompting', source: 'this studio; grammar after lumosai8/MinimaxStoryBuilder prompts.py and Comfy-Org/docs minimax-h3', sourceVersion: '2026-10', supportedModels: ['MiniMax-H3 (local, ComfyUI)', 'MiniMax Hailuo (hosted)'], requiredTools: ['video.minimax_generate'], status: 'VALIDATED' },
  { id: 'audio-first-dialogue', name: 'Audio-first speaking shots', path: 'skills/audio-first-dialogue', source: 'this studio (docs/AUDIOVISUAL-QA.md experiments E0–E2c)', sourceVersion: '2026-10', supportedModels: ['MiniMax-H3 (local, ComfyUI)', 'IndexTTS 2.5', 'Habibi-TTS IRQ'], requiredTools: ['speech.synthesize', 'speech.transcribe', 'video.minimax_generate'], status: 'VALIDATED' },
  { id: 'iraqi-dialogue', name: 'Iraqi Arabic dialogue', path: 'skills/iraqi-dialogue', source: 'this studio; suite docs/evidence/iraqi-suite.md', sourceVersion: '2026-10', supportedModels: ['qwen3:14b', 'Habibi-TTS IRQ', 'IndexTTS 2.5'], requiredTools: ['story.structured_answer', 'speech.synthesize', 'speech.transcribe'], status: 'VALIDATED', note: 'dialect authenticity is reviewed by a native listener; the suite proves intelligibility' },
  { id: 'shot-planning', name: 'Scene-by-scene shot planning', path: 'skills/shot-planning', source: 'this studio; staging rules after MinimaxStoryBuilder SYSTEM_PROMPTS (cast → outline → stage)', sourceVersion: '2026-10', supportedModels: ['qwen3:14b', 'any JSON-capable LLM'], requiredTools: ['story.structured_answer', 'studio.command'], status: 'VALIDATED' },
  { id: 'screenwriting', name: 'Screenwriting for generated film', path: 'skills/screenwriting', source: 'this studio', sourceVersion: '2026-10', supportedModels: ['qwen3:14b', 'any JSON-capable LLM'], requiredTools: ['story.structured_answer'], status: 'VALIDATED' },
  { id: 'world-continuity', name: 'World and location continuity', path: 'skills/world-continuity', source: 'this studio; references-on-every-shot rule after MinimaxStoryBuilder', sourceVersion: '2026-10', supportedModels: ['Qwen-Image-Edit-2511', 'MiniMax-H3 (local, ComfyUI)'], requiredTools: ['image.edit_with_references', 'studio.read'], status: 'VALIDATED' },
  { id: 'singing-performance', name: 'Singing performance and lyric timing', path: 'skills/singing-performance', source: 'this studio', sourceVersion: '2026-10', supportedModels: ['qwen3:14b', 'faster-whisper large-v3'], requiredTools: ['story.structured_answer', 'speech.transcribe', 'lyrics.align'], status: 'VALIDATED' },
  { id: 'audio-mix-policy', name: 'Authoritative audio tracks and mix policy', path: 'skills/audio-mix-policy', source: 'this studio', sourceVersion: '2026-10', supportedModels: ['ffmpeg'], requiredTools: ['media.assemble', 'media.align_lag'], status: 'VALIDATED' },
  { id: 'take-inspection', name: 'Take inspection and failure classes', path: 'skills/take-inspection', source: 'this studio', sourceVersion: '2026-10', supportedModels: ['ffmpeg', 'faster-whisper large-v3'], requiredTools: ['media.qa_take', 'speech.transcribe', 'media.probe'], status: 'VALIDATED' },
  { id: 'minimax-multimodal-toolkit', name: 'MiniMax multimodal toolkit (hosted)', path: 'skills/minimax-multimodal-toolkit', source: 'github.com/MiniMax-AI/skills', sourceVersion: 'main @ 2026-10 (read, not installed)', supportedModels: ['MiniMax hosted API'], requiredTools: ['video.minimax_generate'], status: 'UNAVAILABLE', note: 'wraps the hosted MiniMax API (video, speech, music, image); this machine has no MINIMAX_API_KEY, so it cannot be validated here' },
  { id: 'minimax-music-gen', name: 'MiniMax music generation (hosted)', path: 'skills/minimax-music-gen', source: 'github.com/MiniMax-AI/skills', sourceVersion: 'main @ 2026-10 (read, not installed)', supportedModels: ['MiniMax Music API'], requiredTools: ['music.generate'], status: 'UNAVAILABLE', note: 'needs a MiniMax API key' },
];

// --------------------------------------------------------------------------------------------------------- agents

const S = (text: string) => text.replace(/\s+/g, ' ').trim();

export const AGENTS: AgentDef[] = [
  // Executive Office
  { id: 'studio-director', name: 'Studio Director', department: 'EXECUTIVE', role: 'Overall creative direction', description: 'Holds the creative standard of every production: style, tone, consistency across departments; final creative call inside the approved brief.', systemInstructions: S(`You direct the studio. Keep every department to the production's approved brief, visual direction and language. Resolve cross-department conflicts; never redesign an approved character or place.`), model: 'rule set + human approvals', skills: ['screenwriting', 'world-continuity'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'Decision', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['approved brief respected', 'one visual direction per production'], jobTypes: [] },
  { id: 'executive-producer', name: 'Executive Producer', department: 'EXECUTIVE', role: 'Feasibility, resources, schedule, delivery', description: 'Decides what can be made with the machine at hand: GPU budget, time per shot, running time, scope.', systemInstructions: S(`Plan within one RTX 5090: one video generation at a time; a 5 s take costs ≈75–130 s of engine time, a 10 s take ≈4–7 min. Keep productions deliverable.`), model: 'rule set', skills: [], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'Feasibility', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['every production has a feasible plan and an expected duration'], jobTypes: [] },
  { id: 'production-coordinator', name: 'Production Coordinator', department: 'EXECUTIVE', role: 'Dependencies, handoffs, assignments, progress, escalation', description: 'Runs the pipeline: queues the department jobs in dependency order, records handoffs, waits, reports blockers.', systemInstructions: S(`Advance a production through the pipeline stages. Queue durable jobs with idempotency keys, adopt in-flight children after a restart, let a continuation shot wait for the shot it continues, record every handoff, never let an invalid handoff pass downstream.`), model: 'deterministic orchestrator', skills: [], tools: ['jobs.enqueue', 'studio.read', 'studio.command'], inputSchema: 'ProduceInput', outputSchema: 'ProduceOutput', limits: { timeoutMs: 7_200_000, maxAttempts: 3, resource: 'CPU' }, version: '2.0.0', qualityRequirements: ['no duplicate generation in flight for one shot', 'every stage ends in a handoff'], jobTypes: ['PRODUCE'] },
  { id: 'quality-director', name: 'Quality Director', department: 'EXECUTIVE', role: 'Acceptance policy, quality gates, production readiness', description: 'Owns the thresholds the inspectors apply and the final readiness decision; independent of the producing departments.', systemInstructions: S(`Apply the acceptance policy: a take passes only on its measured checks; a cut or export only after validation; subjective judgements (acting, dialect, style) go to a human.`), model: 'rule set', skills: ['take-inspection'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'Readiness', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['thresholds are never lowered to pass material'], jobTypes: [] },
  // Story Development
  { id: 'head-of-story', name: 'Head of Story', department: 'STORY', role: 'Director: story structure, character development, narrative quality', description: 'Develops a brief into a story with scenes and the cast and places it needs; owns the Story Bible.', systemInstructions: S(`From the producer's brief and the show's World Bible, develop the story: logline, synopsis, scene breakdown with purpose, emotional objective, entry and exit states. An episode is carried by its show's regulars; outside characters only when the brief names them.`), model: 'qwen3:14b (Ollama) or the configured hosted LLM', skills: ['screenwriting', 'world-continuity'], tools: ['story.structured_answer', 'studio.read', 'studio.command'], inputSchema: 'DevelopInput', outputSchema: 'DevelopOutput', limits: { timeoutMs: 600_000, maxAttempts: 3, resource: 'LLM' }, version: '2.0.0', qualityRequirements: ['every scene producible in 4–15 s shots', 'cast resolved by id'], jobTypes: ['DEVELOP_STORY', 'AUTO_IDEA'] },
  { id: 'creative-research', name: 'Creative Research Agent', department: 'STORY', role: 'References, genre conventions, cultural context', description: 'Collects the references the writers draw on and marks what is research and what is invention.', systemInstructions: S(`Gather producer-supplied references and genre conventions for the brief; label research-supported facts apart from original ideas. Web research only when the producer enables it.`), model: 'qwen3:14b (Ollama)', skills: ['screenwriting'], tools: ['story.structured_answer', 'studio.read'], inputSchema: 'ResearchInput', outputSchema: 'ResearchNotes', limits: { timeoutMs: 300_000, maxAttempts: 2, resource: 'LLM' }, version: '1.0.0', qualityRequirements: ['claims marked as researched or invented'], jobTypes: [] },
  { id: 'screenwriter', name: 'Screenwriter', department: 'STORY', role: 'Scripts, dialogue, scene descriptions', description: 'Writes beats and lines for every scene in the production’s language and dialect, with an English gloss for review.', systemInstructions: S(`Write what we see (present tense, filmable in seconds) and short lines (spoken in under 6 s). Arabic productions: the dialect in textAr, a faithful English gloss in text. Never paraphrase an approved line later.`), model: 'qwen3:14b (Ollama) or the configured hosted LLM', skills: ['screenwriting', 'iraqi-dialogue'], tools: ['story.structured_answer', 'studio.command'], inputSchema: 'WriteScriptInput', outputSchema: 'WriteScriptOutput', limits: { timeoutMs: 600_000, maxAttempts: 3, resource: 'LLM' }, version: '2.0.0', qualityRequirements: ['every line glossed', 'lines ≤ 6 s spoken'], jobTypes: ['WRITE_SCRIPT'] },
  { id: 'story-editor', name: 'Story Editor', department: 'STORY', role: 'Logic, pacing, motivation, contradictions', description: 'Checks a script for contradictions, repetition and missing purpose before it goes to pre-production.', systemInstructions: S(`Read the developed story and script against the World Bible and the earlier episodes; flag contradictions, repeated beats, scenes without purpose; propose minimal fixes.`), model: 'qwen3:14b (Ollama)', skills: ['screenwriting'], tools: ['story.structured_answer', 'studio.read'], inputSchema: 'ProductionRef', outputSchema: 'EditorNotes', limits: { timeoutMs: 300_000, maxAttempts: 2, resource: 'LLM' }, version: '1.0.0', qualityRequirements: ['no unresolved contradiction in a handed-off script'], jobTypes: [] },
  { id: 'continuity-writer', name: 'Continuity Writer', department: 'STORY', role: 'Story continuity across scenes, episodes, seasons', description: 'Keeps the Story Bible: what has happened, who knows what, where things are.', systemInstructions: S(`After each episode, record the events and states later episodes must respect in the show's World Bible timeline.`), model: 'qwen3:14b (Ollama)', skills: ['world-continuity'], tools: ['story.structured_answer', 'studio.read', 'studio.command'], inputSchema: 'ProductionRef', outputSchema: 'BibleUpdate', limits: { timeoutMs: 300_000, maxAttempts: 2, resource: 'LLM' }, version: '1.1.0', qualityRequirements: ['timeline entries per finished episode', 'open storylines carried to the next episode'], jobTypes: ['EPISODE_CONTINUITY'] },
  // Casting & Character Design
  { id: 'casting-director', name: 'Casting Director', department: 'CASTING', role: 'Director: required cast, canonical identities', description: 'Resolves who is in a production by stable id, creates new characters only when the story needs them, guards the appearance lock.', systemInstructions: S(`Cast by id, never by fuzzy name alone; a library id is trusted only when the name agrees. A character used in a video keeps its appearance.`), model: 'qwen3:14b (Ollama) + rule set', skills: ['world-continuity', 'screenwriting'], tools: ['story.structured_answer', 'studio.read', 'studio.command'], inputSchema: 'CastingInput', outputSchema: 'CastingOutput', limits: { timeoutMs: 300_000, maxAttempts: 3, resource: 'LLM' }, version: '1.1.0', qualityRequirements: ['one seat per character', 'APPEARANCE_LOCKED and VOICE_LOCKED respected', 'a designed character has every appearance field'], jobTypes: ['DESIGN_CHARACTER'] },
  { id: 'character-designer', name: 'Character Designer', department: 'CASTING', role: 'Appearance, proportions, wardrobe, reference sheets', description: 'Draws the portrait and the reference views (front, three-quarter, side, full body, expressions) in the production’s visual direction.', systemInstructions: S(`Describe the character by appearance, never by name; one identity across every view; plain background; the direction's style words first.`), model: 'Qwen-Image-2512 / Qwen-Image-Edit-2511 (ComfyUI)', skills: ['world-continuity'], tools: ['image.generate', 'image.edit_with_references', 'studio.command'], inputSchema: 'CharacterArtInput', outputSchema: 'CharacterArtOutput', limits: { timeoutMs: 1_200_000, maxAttempts: 2, resource: 'GPU_IMAGE' }, version: '1.1.0', qualityRequirements: ['identity holds across the sheet'], jobTypes: ['CHARACTER_APPEARANCE', 'CHARACTER_REFS'] },
  { id: 'voice-casting', name: 'Voice Casting Agent', department: 'CASTING', role: 'Persistent voice identity', description: 'Builds and pins a character’s voice from an approved reference recording and proves it with a transcribed line.', systemInstructions: S(`Clone from the chosen recording (Arabic reference for Iraqi voices); speak a proof line; verify by transcription; pin the identity with its revision.`), model: 'IndexTTS 2.5 / Habibi-TTS IRQ + faster-whisper', skills: ['iraqi-dialogue'], tools: ['speech.synthesize', 'speech.clone_voice', 'speech.transcribe', 'studio.command'], inputSchema: 'VoiceBuildInput', outputSchema: 'VoiceBuildOutput', limits: { timeoutMs: 900_000, maxAttempts: 2, resource: 'TTS' }, version: '1.1.0', qualityRequirements: ['proof line WER ≤ 0.35'], jobTypes: ['VOICE_BUILD'] },
  { id: 'character-continuity', name: 'Character Continuity Agent', department: 'CASTING', role: 'Identity stable across productions', description: 'Supplies the approved references for every shot a character is in and records usage; reports drift to QA.', systemInstructions: S(`For every shot, hand the portrait and sheet of each character in it to the reference conditioning; record every take a character appears in.`), model: 'rule set', skills: ['world-continuity'], tools: ['studio.read'], inputSchema: 'ShotRef', outputSchema: 'ReferenceSet', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['references on every shot'], jobTypes: [] },
  // World Building & Art Direction
  { id: 'art-director', name: 'Art Director', department: 'WORLD', role: 'Director: the visual language', description: 'Owns the production direction (cartoon / anime / realistic) and the art direction entry of the World Bible.', systemInstructions: S(`One visual language per production; it leads every image and video prompt.`), model: 'rule set', skills: ['world-continuity'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'ArtDirection', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['style words identical across a production'], jobTypes: [] },
  { id: 'world-designer', name: 'World Designer', department: 'WORLD', role: 'Architecture, geography, rules of the world', description: 'Creates new places from the story’s needs with layout, landmarks and props; keeps the World Bible rules.', systemInstructions: S(`A new place gets description, kind, landmarks, props, layout (geography, architecture, materials, camera zones, entrances). Existing places are reused by id.`), model: 'qwen3:14b (Ollama)', skills: ['world-continuity'], tools: ['story.structured_answer', 'studio.command'], inputSchema: 'WorldInput', outputSchema: 'WorldOutput', limits: { timeoutMs: 300_000, maxAttempts: 2, resource: 'LLM' }, version: '1.0.0', qualityRequirements: ['every place has a layout'], jobTypes: [] },
  { id: 'environment-artist', name: 'Environment Artist', department: 'WORLD', role: 'Canonical location plates', description: 'Draws the master plate and the views (reverse angle, landmark, time-of-day states) of a place, unoccupied.', systemInstructions: S(`Plates show the place before anyone arrives: pure environment and props, the same architecture in every view.`), model: 'Qwen-Image-2512 / Qwen-Image-Edit-2511 (ComfyUI)', skills: ['world-continuity'], tools: ['image.generate', 'image.edit_with_references', 'studio.command'], inputSchema: 'PlatesInput', outputSchema: 'PlatesOutput', limits: { timeoutMs: 1_200_000, maxAttempts: 2, resource: 'GPU_IMAGE' }, version: '1.1.0', qualityRequirements: ['no figures in a plate', 'architecture identical across views'], jobTypes: ['LOCATION_PLATES'] },
  { id: 'set-designer', name: 'Set Designer', department: 'WORLD', role: 'Spatial layouts and recurring physical elements', description: 'Maintains each place’s layout record: entrances, zones, fixed furniture, materials.', systemInstructions: S(`Keep the layout of every place current; permanent architecture never changes without a story reason.`), model: 'rule set + qwen3:14b', skills: ['world-continuity'], tools: ['studio.read', 'studio.command'], inputSchema: 'LocationRef', outputSchema: 'LayoutRecord', limits: { timeoutMs: 120_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['layout present for every used place'], jobTypes: [] },
  { id: 'props-designer', name: 'Props Designer', department: 'WORLD', role: 'Recurring objects and their persistent look', description: 'Keeps the props established at each place and in each character’s hands, with their state.', systemInstructions: S(`Track the props the shot continuity names; a prop keeps its look and its last known position and state.`), model: 'rule set', skills: ['world-continuity'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'PropsRecord', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['props state carried between scenes'], jobTypes: [] },
  { id: 'world-continuity', name: 'World Continuity Agent', department: 'WORLD', role: 'Environments stable throughout the film', description: 'Tells the planner what was established at a returning place and hands the plates to every shot there.', systemInstructions: S(`A returning place is the same place: same plates by id, same architecture; only light, weather, time and movable things may change, and the shots say how.`), model: 'rule set', skills: ['world-continuity'], tools: ['studio.read'], inputSchema: 'SceneRef', outputSchema: 'EstablishedState', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['plates reused by id on return'], jobTypes: [] },
  // Pre-Production
  { id: 'film-director', name: 'Film Director', department: 'PREPRODUCTION', role: 'Director: the visual execution plan', description: 'Turns the script into scenes of shots with purpose, staging and continuity states; owns the production plan.', systemInstructions: S(`Every shot has a purpose; faces close when someone is on screen; keep the 180° line; mark continuation, cut or story transition; no shot without a reason.`), model: 'qwen3:14b (Ollama) or the configured hosted LLM', skills: ['shot-planning', 'h3-prompting'], tools: ['story.structured_answer', 'studio.read', 'studio.command'], inputSchema: 'PlanShotsInput', outputSchema: 'PlanShotsOutput', limits: { timeoutMs: 900_000, maxAttempts: 3, resource: 'LLM' }, version: '2.0.0', qualityRequirements: ['every line assigned to exactly one shot', 'scene fills its budget'], jobTypes: ['PLAN_SHOTS'] },
  { id: 'storyboard-artist', name: 'Storyboard Artist', department: 'PREPRODUCTION', role: 'Shot references and storyboard frames', description: 'Draws each shot’s opening frame from the location plate and the characters’ portraits.', systemInstructions: S(`Image 1 is the exact place; the following images are the people: keep face, hair, skin and wardrobe exactly.`), model: 'Qwen-Image-Edit-2511 (ComfyUI)', skills: ['world-continuity'], tools: ['image.edit_with_references', 'image.generate', 'studio.command'], inputSchema: 'FramesInput', outputSchema: 'FramesOutput', limits: { timeoutMs: 600_000, maxAttempts: 2, resource: 'GPU_IMAGE' }, version: '1.1.0', qualityRequirements: ['frame built from the plate and portraits when they exist'], jobTypes: ['SHOT_FRAMES'] },
  { id: 'cinematographer', name: 'Cinematographer', department: 'PREPRODUCTION', role: 'Composition, angles, movement, lens, screen direction', description: 'Sets framing, camera move, lens intent and angle for every shot inside the plan.', systemInstructions: S(`Framing and movement serve the beat; faces large in frame when a character speaks; consistent screen direction.`), model: 'qwen3:14b (within the shot plan)', skills: ['shot-planning'], tools: ['story.structured_answer'], inputSchema: 'SceneRef', outputSchema: 'CameraPlan', limits: { timeoutMs: 300_000, maxAttempts: 2, resource: 'LLM' }, version: '1.0.0', qualityRequirements: ['framing and move on every shot'], jobTypes: [] },
  { id: 'shot-planner', name: 'Shot Planner', department: 'PREPRODUCTION', role: 'Executable shot specifications', description: 'Fits durations to the scene budget, assigns lines, writes the generation prompt and the continuity entry/exit state per shot.', systemInstructions: S(`A shot specification names scene, characters by id, location by id, references, duration, action, camera, audio needs, continuity entry and exit. Nothing incomplete reaches production.`), model: 'deterministic + qwen3:14b', skills: ['shot-planning', 'h3-prompting'], tools: ['studio.command', 'studio.read'], inputSchema: 'SceneRef', outputSchema: 'ShotSpecs', limits: { timeoutMs: 300_000, maxAttempts: 2, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['durations 3–15 s', 'budget filled ≥ 90 %'], jobTypes: [] },
  { id: 'production-planner', name: 'Production Planner', department: 'PREPRODUCTION', role: 'Workload, duration, resources, audio dependencies', description: 'Counts shots, seconds and expected engine time; lists what audio must exist before video.', systemInstructions: S(`Expected duration = Σ per-shot engine time by length; speaking shots need their recordings first; music videos need the song and its alignment first.`), model: 'deterministic', skills: [], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'WorkloadPlan', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['expected duration shown before production starts'], jobTypes: [] },
  // Video Production
  { id: 'production-director', name: 'Production Director', department: 'VIDEO', role: 'Director: supervises shot generation', description: 'Supervises the generation of every take against the approved plan.', systemInstructions: S(`Generate what the plan says; never let the engine override the approved shot; one generation in flight per shot.`), model: 'rule set', skills: ['h3-prompting'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'Supervision', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['plan respected'], jobTypes: [] },
  { id: 'minimax-video-specialist', name: 'MiniMax Video Specialist', department: 'VIDEO', role: 'Model selection, request construction, parameters', description: 'Builds the MiniMax H3 request for a shot: graph (first/last frame or reference-to-video), guides, length on the 17k+5 grid, steps, seed; runs it; records provenance.', systemInstructions: S(`MiniMax only. The exact script lines in the <d> tags; a drawn opening frame as first frame; otherwise portraits and the plate as references; recorded lines and the previous take's tail as guides; length from the words; seed recorded.`), model: 'MiniMax-H3 (local, ComfyUI 0.38.1, int8 pruned, turbo LoRAs) / hosted MiniMax when a key exists', skills: ['h3-prompting', 'audio-first-dialogue'], tools: ['video.minimax_generate', 'speech.synthesize', 'speech.transcribe', 'media.probe', 'media.qa_take', 'studio.read', 'studio.command'], inputSchema: 'TakeInput', outputSchema: 'TakeOutput', limits: { timeoutMs: 5_400_000, maxAttempts: 3, resource: 'GPU_VIDEO' }, version: '3.0.0', qualityRequirements: ['provenance complete', 'no paraphrased dialogue'], jobTypes: ['GENERATE_TAKE'] },
  { id: 'reference-conditioning', name: 'Reference Conditioning Agent', department: 'VIDEO', role: 'Selects and validates references', description: 'Chooses the right pictures, audio and frames for a shot within the engine’s limits (9 pictures, 3 audio).', systemInstructions: S(`Opening frame first; then each character's portrait; then the plate; voice samples for speakers; never a bundled sample picture; respect the limits.`), model: 'rule set', skills: ['world-continuity', 'h3-prompting'], tools: ['studio.read'], inputSchema: 'ShotRef', outputSchema: 'ReferenceSet', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['references within limits, all usable'], jobTypes: [] },
  { id: 'motion-director', name: 'Motion Director', department: 'VIDEO', role: 'Movement and action continuity', description: 'Keeps action continuous across a continuation: the previous tail as the next head.', systemInstructions: S(`A continuation shot starts from the last 22 frames and the sound of the previous take; those frames are dropped in the cut.`), model: 'rule set', skills: ['h3-prompting'], tools: ['studio.read'], inputSchema: 'ShotRef', outputSchema: 'MotionPlan', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['continuation guides applied in order'], jobTypes: [] },
  { id: 'performance-director', name: 'Performance Director', department: 'VIDEO', role: 'Expressions, acting, speaking, singing', description: 'Sets who speaks or sings on screen and who stays silent; the recorded line is the performance reference.', systemInstructions: S(`Only the assigned performer in the shot sings; listeners keep lips closed; a speaking shot follows its recorded line.`), model: 'rule set', skills: ['audio-first-dialogue', 'singing-performance'], tools: ['studio.read'], inputSchema: 'ShotRef', outputSchema: 'PerformanceSpec', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['performance spec per speaking/singing shot'], jobTypes: [] },
  { id: 'rendering-engineer', name: 'Rendering Engineer', department: 'VIDEO', role: 'Execution, retrieval, validation, resources', description: 'Runs the graph under the GPU lease, resumes a prompt after a restart, retrieves and probes the file.', systemInstructions: S(`One model family on the card at a time; record the prompt id as soon as it exists; never resubmit a prompt the engine still knows.`), model: 'ComfyUI 0.38.1 on the RTX 5090', skills: [], tools: ['video.minimax_generate', 'media.probe'], inputSchema: 'GraphRef', outputSchema: 'RenderOutput', limits: { timeoutMs: 5_400_000, maxAttempts: 3, resource: 'GPU_VIDEO' }, version: '1.0.0', qualityRequirements: ['no duplicate prompt after a restart'], jobTypes: [] },
  // Sound & Music
  { id: 'sound-director', name: 'Sound Director', department: 'SOUND', role: 'Director: the entire audio design', description: 'Owns the authoritative audio timeline and the mix policy: which sound is the soundtrack of each stretch.', systemInstructions: S(`One authoritative sound per stretch: the song master in a music video; a take's own sound (carrying its recorded line) in a film; recorded lines only under silent takes; a source appears once.`), model: 'rule set', skills: ['audio-mix-policy'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'MixPolicy', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['no doubled song or vocals'], jobTypes: [] },
  { id: 'dialogue-director', name: 'Dialogue Director', department: 'SOUND', role: 'Speech performance', description: 'Records every line with its character’s canonical voice, checks each by transcription, regenerates a drifting line once, flags the rest.', systemInstructions: S(`Record in the production's language; verify by transcription (WER ≤ 0.35); a flagged line goes to review, never silently accepted.`), model: 'IndexTTS 2.5 / Habibi-TTS IRQ + faster-whisper', skills: ['audio-first-dialogue', 'iraqi-dialogue'], tools: ['speech.synthesize', 'speech.transcribe', 'studio.command'], inputSchema: 'DialogueAudioInput', outputSchema: 'DialogueAudioOutput', limits: { timeoutMs: 1_800_000, maxAttempts: 2, resource: 'TTS' }, version: '1.1.0', qualityRequirements: ['every line transcribed back'], jobTypes: ['DIALOGUE_AUDIO', 'VOICE_PREVIEW'] },
  { id: 'iraqi-specialist', name: 'Iraqi Arabic Language Specialist', department: 'SOUND', role: 'Iraqi wording, dialect, pronunciation, code-switching', description: 'Validates Iraqi lines: wording in the script, intelligibility of the recording, routing of mixed-language lines; keeps the pronunciation suite.', systemInstructions: S(`Iraqi Baghdadi wording (شلونك، هسه، شنو، گ، چ), never MSA; mixed-script lines to the bilingual engine; an Iraqi voice needs an Arabic reference clip. Dialect authenticity is a native listener's call — mark it pending review.`), model: 'faster-whisper large-v3 + rule set (suite: scripts/iraqi-voice-suite.mjs)', skills: ['iraqi-dialogue'], tools: ['speech.synthesize', 'speech.transcribe'], inputSchema: 'LineSet', outputSchema: 'DialectReport', limits: { timeoutMs: 900_000, maxAttempts: 1, resource: 'TTS' }, version: '1.0.0', qualityRequirements: ['suite run per voice change'], jobTypes: [] },
  { id: 'voice-engineer', name: 'Voice Engineer', department: 'SOUND', role: 'Stable character voices', description: 'Keeps each character’s voice identity and reference recording stable across productions.', systemInstructions: S(`One pinned voice per character; the same reference across every line and episode.`), model: 'rule set', skills: ['audio-first-dialogue'], tools: ['studio.read'], inputSchema: 'CharacterRef', outputSchema: 'VoiceState', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['identity revision recorded'], jobTypes: [] },
  { id: 'music-director', name: 'Music Director', department: 'SOUND', role: 'Soundtrack and song generation', description: 'Composes the song from the caption and lyrics, separates stems, places the lyrics on the vocal track.', systemInstructions: S(`ACE-Step 1.5 by default, MiniMax Music 3 as the second local engine, the MiniMax Music API when a key exists; tempo and key from the caption; stems; align the written lines to the sung vocal.`), model: 'ACE-Step 1.5 XL turbo / MiniMax Music 3 (ComfyUI) + Demucs + faster-whisper', skills: ['singing-performance'], tools: ['music.generate', 'audio.separate_stems', 'speech.transcribe', 'lyrics.align', 'studio.command'], inputSchema: 'SongInput', outputSchema: 'SongOutput', limits: { timeoutMs: 1_800_000, maxAttempts: 2, resource: 'GPU_IMAGE' }, version: '1.2.0', qualityRequirements: ['vocals sing the written lyrics (transcribed)', 'stems present'], jobTypes: ['GENERATE_SONG'] },
  { id: 'singing-performance', name: 'Singing Performance Agent', department: 'SOUND', role: 'Phrases mapped to performers', description: 'Assigns each section to its singers (solo, duet, alternating, ensemble, instrumental) from the lyrics and the story, and copies the assignment onto the shots.', systemInstructions: S(`A wizard's "everyone sings everything" is a placeholder, not a decision: decide from the lyrics and the story; only an assigned performer sings in a shot.`), model: 'qwen3:14b (Ollama) + faster-whisper', skills: ['singing-performance'], tools: ['story.structured_answer', 'lyrics.align', 'speech.transcribe', 'studio.command'], inputSchema: 'PerformanceInput', outputSchema: 'PerformancePlan', limits: { timeoutMs: 600_000, maxAttempts: 2, resource: 'LLM' }, version: '1.1.0', qualityRequirements: ['every section assigned'], jobTypes: [] },
  { id: 'audio-engineer', name: 'Audio Engineer', department: 'SOUND', role: 'Separation, timing, editing, mixing, loudness, sync', description: 'Builds the typed mix plan at sample offsets, measures sound-to-picture lag, brings loudness to target.', systemInstructions: S(`Whole frames and whole samples; every track from its source once; EBU R128 to the target; measure, never stretch.`), model: 'ffmpeg + rule set', skills: ['audio-mix-policy'], tools: ['media.align_lag', 'media.assemble', 'audio.separate_stems'], inputSchema: 'MixInput', outputSchema: 'MixPlan', limits: { timeoutMs: 3_600_000, maxAttempts: 2, resource: 'CPU' }, version: '2.0.0', qualityRequirements: ['audio/video length within a frame'], jobTypes: [] },
  // Post-Production
  { id: 'post-director', name: 'Post-Production Director', department: 'POST', role: 'Director: the completed film assembly', description: 'Supervises cut, mix, subtitles and export; owns the Edit and Export stages.', systemInstructions: S(`Assemble only validated takes; export only a validated cut.`), model: 'rule set', skills: ['audio-mix-policy'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'PostPlan', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['no sample take in a cut'], jobTypes: [] },
  { id: 'video-editor', name: 'Video Editor', department: 'POST', role: 'Shot selection, timing, cuts', description: 'Joins the chosen takes frame-exactly, drops continuation heads, aligns performers to the master, builds the cut.', systemInstructions: S(`The cut clock is whole frames; a continuation's repeated frames are dropped; a late performer loses head frames, nothing is stretched.`), model: 'ffmpeg', skills: ['audio-mix-policy'], tools: ['media.assemble', 'media.align_lag', 'media.probe', 'media.validate_export', 'studio.command'], inputSchema: 'AssembleInput', outputSchema: 'AssembleOutput', limits: { timeoutMs: 3_600_000, maxAttempts: 2, resource: 'CPU' }, version: '2.0.0', qualityRequirements: ['cut validated'], jobTypes: ['ASSEMBLE'] },
  { id: 'continuity-editor', name: 'Continuity Editor', department: 'POST', role: 'Shot-to-shot transitions', description: 'Inspects joins: screen direction, wardrobe, props, light between consecutive shots.', systemInstructions: S(`Compare each join with the planned relation (continuation, cut, transition) and the continuity states; report breaks.`), model: 'rule set (planned: vision model)', skills: ['world-continuity'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'JoinReport', limits: { timeoutMs: 300_000, maxAttempts: 1, resource: 'NONE' }, version: '0.9.0', qualityRequirements: ['every join reviewed'], jobTypes: [] },
  { id: 'audio-mixing-engineer', name: 'Audio Mixing Engineer', department: 'POST', role: 'The final mix', description: 'Renders the mix plan: tracks at sample offsets, policies applied, loudness normalised.', systemInstructions: S(`Render exactly the plan; report the measured loudness and true peak.`), model: 'ffmpeg', skills: ['audio-mix-policy'], tools: ['media.assemble'], inputSchema: 'MixPlan', outputSchema: 'MixRender', limits: { timeoutMs: 3_600_000, maxAttempts: 2, resource: 'CPU' }, version: '1.0.0', qualityRequirements: ['−23 LUFS films / −14 LUFS music videos, TP ≤ −1'], jobTypes: [] },
  { id: 'colorist', name: 'Colorist', department: 'POST', role: 'Consistent colour and exposure', description: 'Conforms every take to one colour space and letterboxes uniformly.', systemInstructions: S(`bt709, yuv420p, one size per cut.`), model: 'ffmpeg', skills: [], tools: ['media.assemble'], inputSchema: 'AssembleInput', outputSchema: 'ConformReport', limits: { timeoutMs: 600_000, maxAttempts: 1, resource: 'CPU' }, version: '0.9.0', qualityRequirements: ['uniform conform'], jobTypes: [] },
  { id: 'subtitle-specialist', name: 'Subtitle Specialist', department: 'POST', role: 'Accurate English and Arabic subtitles', description: 'Writes cues from the takes’ real line windows and the aligned lyrics; RTL marks for Arabic; SRT and VTT sidecars; burn-in on export.', systemInstructions: S(`One cue per spoken line at its measured window; one cue per lyric line on the vocal's timing; Arabic cues start with a right-to-left mark.`), model: 'rule set', skills: ['singing-performance'], tools: ['studio.read'], inputSchema: 'ProductionRef', outputSchema: 'CueSet', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.1.0', qualityRequirements: ['cues from measured timings when available'], jobTypes: [] },
  { id: 'export-engineer', name: 'Export Engineer', department: 'POST', role: 'Final media', description: 'Renders the delivery file at the chosen size and codec and validates it before recording it.', systemInstructions: S(`H.264/H.265/ProRes at 720/1080/2160; faststart; validate lengths, rate, size, timestamps, black stretches; a failed check fails the export.`), model: 'ffmpeg', skills: ['audio-mix-policy'], tools: ['media.assemble', 'media.align_lag', 'media.probe', 'media.validate_export', 'studio.command'], inputSchema: 'ExportInput', outputSchema: 'ExportOutput', limits: { timeoutMs: 3_600_000, maxAttempts: 2, resource: 'CPU' }, version: '2.0.0', qualityRequirements: ['validation passed'], jobTypes: ['EXPORT'] },
  // Quality Assurance (independent)
  { id: 'character-consistency-inspector', name: 'Character Consistency Inspector', department: 'QA', role: 'Character identity in takes', description: 'Compares a take’s poster frame with the character sheet; reports identity drift.', systemInstructions: S(`Face, hair, skin, wardrobe against the approved sheet; report drift as CHARACTER_INCONSISTENCY.`), model: 'human review (planned: vision model)', skills: ['take-inspection'], tools: ['studio.read'], inputSchema: 'TakeRef', outputSchema: 'InspectionReport', limits: { timeoutMs: 300_000, maxAttempts: 1, resource: 'NONE' }, version: '0.9.0', qualityRequirements: ['contact sheet per production'], jobTypes: [] },
  { id: 'world-continuity-inspector', name: 'World Continuity Inspector', department: 'QA', role: 'Environments and locations', description: 'Checks a take’s place against the plates; reports architecture changes.', systemInstructions: S(`Same architecture, layout and fixed props as the plates; report ENVIRONMENT_INCONSISTENCY.`), model: 'human review (planned: vision model)', skills: ['take-inspection'], tools: ['studio.read'], inputSchema: 'TakeRef', outputSchema: 'InspectionReport', limits: { timeoutMs: 300_000, maxAttempts: 1, resource: 'NONE' }, version: '0.9.0', qualityRequirements: ['returning places reviewed'], jobTypes: [] },
  { id: 'audio-sync-inspector', name: 'Audio Synchronization Inspector', department: 'QA', role: 'Dialogue and soundtrack timing', description: 'Transcribes each speaking take and compares it with the script; measures a performer’s lag against the song master.', systemInstructions: S(`Coverage ≥ 0.7 of the script in order; lag against the master within ±60 ms after alignment; report LIP_SYNC_FAILURE / AUDIO_DUPLICATION.`), model: 'faster-whisper large-v3 + ffmpeg', skills: ['take-inspection'], tools: ['speech.transcribe', 'media.align_lag', 'media.probe'], inputSchema: 'TakeRef', outputSchema: 'InspectionReport', limits: { timeoutMs: 600_000, maxAttempts: 1, resource: 'ASR' }, version: '1.0.0', qualityRequirements: ['every speaking take transcribed'], jobTypes: [] },
  { id: 'lipsync-inspector', name: 'Lip-Sync Inspector', department: 'QA', role: 'Speaking and singing synchronisation', description: 'Reviews mouth motion against the spoken or sung windows; frame-level review for suspect takes.', systemInstructions: S(`A still cannot prove sync; review at speed and frame by frame around onsets and phrase ends; automatic scores are supporting evidence.`), model: 'human review + envelope measurements', skills: ['take-inspection'], tools: ['media.align_lag', 'studio.read'], inputSchema: 'TakeRef', outputSchema: 'InspectionReport', limits: { timeoutMs: 600_000, maxAttempts: 1, resource: 'NONE' }, version: '0.9.0', qualityRequirements: ['review recorded per speaking/singing take'], jobTypes: [] },
  { id: 'visual-quality-inspector', name: 'Visual Quality Inspector', department: 'QA', role: 'Anatomy, motion, artefacts, image quality', description: 'Runs the measured picture checks (black, frozen, flicker, duration, size) and reviews anatomy and morphing.', systemInstructions: S(`Measured checks first; int8 morphing near the end of a clip is a known failure class; report OUTPUT_CORRUPTION or VISUAL_ARTIFACT.`), model: 'ffmpeg + human review', skills: ['take-inspection'], tools: ['media.qa_take', 'media.probe'], inputSchema: 'TakeRef', outputSchema: 'InspectionReport', limits: { timeoutMs: 300_000, maxAttempts: 1, resource: 'CPU' }, version: '1.0.0', qualityRequirements: ['every take checked'], jobTypes: [] },
  { id: 'technical-media-inspector', name: 'Technical Media Inspector', department: 'QA', role: 'Codecs, rates, timestamps, integrity', description: 'Validates every cut and export: lengths within a frame, frame rate, size, timestamps, black stretches.', systemInstructions: S(`Nothing is recorded as a cut or export without passing validation.`), model: 'ffprobe/ffmpeg', skills: ['take-inspection'], tools: ['media.validate_export', 'media.probe'], inputSchema: 'FileRef', outputSchema: 'ExportValidation', limits: { timeoutMs: 600_000, maxAttempts: 1, resource: 'CPU' }, version: '1.0.0', qualityRequirements: ['validation on every finished file'], jobTypes: [] },
  { id: 'reliability-engineer', name: 'Reliability Engineer', department: 'QA', role: 'Failed and repeated attempts', description: 'Opens a reliability event for every second attempt, classifies the root cause, records the change made.', systemInstructions: S(`A second attempt is an event, not a routine; classify (invalid input, capability, reference, plan, prompt, parameters, infrastructure, provider, resources, character, environment, voice, lip-sync, audio duplication, corruption) and record the correction.`), model: 'rule set', skills: ['take-inspection'], tools: ['studio.read'], inputSchema: 'JobRef', outputSchema: 'ReliabilityEvent', limits: { timeoutMs: 60_000, maxAttempts: 1, resource: 'NONE' }, version: '1.0.0', qualityRequirements: ['event per repeated attempt'], jobTypes: [] },
];

export const DEPARTMENTS: DepartmentDef[] = [
  { id: 'EXECUTIVE', name: 'Executive Office', nameAr: 'المكتب التنفيذي', directorId: 'studio-director', responsibility: 'Creative direction, feasibility, coordination and the acceptance policy of every production.', stages: [], order: 0 },
  { id: 'STORY', name: 'Story Development', nameAr: 'تطوير القصة', directorId: 'head-of-story', responsibility: 'Concept, treatment, script and dialogue; the Story Bible.', stages: ['STORY', 'SCRIPT'], order: 1 },
  { id: 'CASTING', name: 'Casting & Character Design', nameAr: 'اختيار وتصميم الشخصيات', directorId: 'casting-director', responsibility: 'Canonical identities: appearance, reference sheets, voice; the Character Bible and the appearance lock.', stages: ['CAST_WORLD'], order: 2 },
  { id: 'WORLD', name: 'World Building & Art Direction', nameAr: 'بناء العالم والتوجيه الفني', directorId: 'art-director', responsibility: 'The visual language, places with plates and layouts, props; the World and Location Bibles.', stages: ['CAST_WORLD'], order: 3 },
  { id: 'PREPRODUCTION', name: 'Pre-Production', nameAr: 'ما قبل الإنتاج', directorId: 'film-director', responsibility: 'Scenes into executable shots with frames, durations, audio needs and continuity states; the production plan.', stages: ['STORYBOARD', 'SHOT_PLAN'], order: 4 },
  { id: 'VIDEO', name: 'Video Production', nameAr: 'إنتاج الفيديو', directorId: 'production-director', responsibility: 'Validated MiniMax takes with complete provenance; MiniMax is the only video engine.', stages: ['VIDEO'], order: 5 },
  { id: 'SOUND', name: 'Sound & Music', nameAr: 'الصوت والموسيقى', directorId: 'sound-director', responsibility: 'Dialogue in the characters’ voices, Iraqi Arabic, songs and stems, the authoritative audio timeline.', stages: ['AUDIO_PREP'], order: 6 },
  { id: 'POST', name: 'Post-Production', nameAr: 'ما بعد الإنتاج', directorId: 'post-director', responsibility: 'The cut, the mix, subtitles and the validated export.', stages: ['EDIT', 'EXPORT'], order: 7 },
  { id: 'QA', name: 'Quality Assurance', nameAr: 'ضمان الجودة', directorId: 'quality-director', responsibility: 'Independent inspection: identity, world, sync, picture, media integrity, reliability; the acceptance decision.', stages: ['QA'], order: 8 },
];

/** Which agent executes a job type. */
export const JOB_AGENT: Record<JobType, string> = Object.fromEntries(AGENTS.flatMap((a) => a.jobTypes.map((t) => [t, a.id]))) as Record<JobType, string>;
JOB_AGENT.MEDIA_PROBE = 'technical-media-inspector';

/** The agent for a concrete job: the type decides, except where the payload names a narrower piece of work. */
export function agentIdForJob(job: { type: JobType; payload: unknown }): string {
  const p = (job.payload ?? {}) as Record<string, unknown>;
  if (job.type === 'PLAN_SHOTS' && p.performanceOnly) return 'singing-performance';
  return JOB_AGENT[job.type];
}

export const FAILURE_CLASSES = ['INVALID_INPUT', 'UNSUPPORTED_CAPABILITY', 'MISSING_REFERENCE', 'INCONSISTENT_PLAN', 'PROMPT_AMBIGUITY', 'WRONG_PARAMETERS', 'INFRASTRUCTURE', 'PROVIDER', 'RESOURCE_EXHAUSTION', 'CHARACTER_INCONSISTENCY', 'ENVIRONMENT_INCONSISTENCY', 'VOICE_MISMATCH', 'LIP_SYNC_FAILURE', 'AUDIO_DUPLICATION', 'OUTPUT_CORRUPTION', 'CANCELLED', 'UNKNOWN'] as const;
export type FailureClass = (typeof FAILURE_CLASSES)[number];

export const agentById = (id: string) => AGENTS.find((a) => a.id === id);
export const departmentById = (id: DepartmentId) => DEPARTMENTS.find((d) => d.id === id);
export const toolById = (id: string) => TOOLS.find((t) => t.id === id);
