#!/usr/bin/env node
/** ONE-COMMAND LOCAL RESUME (cloud directive 2026-10-05 §14) — the workstation is back: check it, start it, resume.
 *
 *    node scripts/resume-local.mjs                 # PLAN: print every step and its command, change nothing
 *    node scripts/resume-local.mjs --go            # run the steps in order, stop at the first failed one
 *    node scripts/resume-local.mjs --go --from comfyui     # restart from a step (after fixing what stopped it)
 *    node scripts/resume-local.mjs --go --start-app        # also start the web server and the worker, detached
 *    node scripts/resume-local.mjs --go --resume-intake    # also open job intake (otherwise it stays paused)
 *
 *  Steps: repository → env files → Docker/WSL memory → RTX 5090 (host and inside a container) → database up and
 *  backed up → migrations → model files verified on the volume → ComfyUI up + every node and model the workflows name
 *  → voice and transcription services → the studio (web, worker) healthy → the acceptance checkpoint read and the
 *  gates printed. Intake stays PAUSED unless --resume-intake: nothing is generated by this script. Every result is
 *  written to var/resume/resume-<time>.json. The judgements are pure and tested (scripts/lib/resume-checks.mjs). */

import { spawnSync, spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { GATES, NEEDS, judgeDocker, judgeGpu, parseDockerInfo, parseNvidiaSmi, parseWslConfig, resumePlan, verifyModels } from './lib/resume-checks.mjs';

const args = process.argv.slice(2);
const GO = args.includes('--go');
const FROM = args.includes('--from') ? args[args.indexOf('--from') + 1] : undefined;
const START_APP = args.includes('--start-app');
const RESUME_INTAKE = args.includes('--resume-intake');
const PROJECT = process.env.COMPOSE_PROJECT ?? 'vewbox';
const STUDIO = (process.env.STUDIO_URL ?? 'http://127.0.0.1:4200').replace(/\/$/, '');
const COMFY = (process.env.COMFYUI_URL ?? 'http://127.0.0.1:8188').replace(/\/$/, '');
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const WIN = process.platform === 'win32';

const run = (cmd, argv, opts = {}) => {
  const r = spawnSync(cmd, argv, { cwd: ROOT, encoding: 'utf8', shell: WIN && /^(pnpm|npx|npm)$/.test(cmd), timeout: opts.timeoutMs ?? 10 * 60_000, maxBuffer: 64 * 1024 * 1024 });
  return { ok: r.status === 0, code: r.status, out: (r.stdout ?? '').trim(), err: (r.stderr ?? '').trim() || (r.error?.message ?? '') };
};
const compose = (...a) => ['compose', '-p', PROJECT, ...a];
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function http(url, timeoutMs = 10_000) { const c = new AbortController(); const t = setTimeout(() => c.abort(), timeoutMs); try { const r = await fetch(url, { signal: c.signal }); return { ok: r.ok, status: r.status, body: await r.text() }; } catch (e) { return { ok: false, status: 0, body: String(e.message ?? e) }; } finally { clearTimeout(t); } }
async function waitHealthy(service, tries = 60) {
  for (let i = 0; i < tries; i++) {
    const r = run('docker', compose('ps', '--format', 'json', service));
    const rows = r.out.split(/\r?\n/).filter(Boolean).map((l) => { try { return JSON.parse(l); } catch { return {}; } });
    const h = rows[0]?.Health ?? rows[0]?.State;
    if (h === 'healthy') return { ok: true, detail: `${service} healthy` };
    if (h === 'exited' || h === 'dead') return { ok: false, detail: `${service} ${h}: docker compose -p ${PROJECT} logs ${service}` };
    await sleep(10_000);
  }
  return { ok: false, detail: `${service} not healthy after ${tries * 10} s: docker compose -p ${PROJECT} logs ${service}` };
}

/** The steps, in order. `cmd` is what PLAN prints; `go` runs it and returns { ok, detail, warn? }. */
const STEPS = [
  { id: 'repo', name: 'Repository on main with the cloud work merged', cmd: 'git fetch origin && git status -sb && git log --oneline -1 origin/cloud-session',
    go: async () => {
      run('git', ['fetch', 'origin']);
      const st = run('git', ['status', '--porcelain']); const br = run('git', ['rev-parse', '--abbrev-ref', 'HEAD']);
      const merged = run('git', ['merge-base', '--is-ancestor', 'origin/cloud-session', 'HEAD']);
      const problems = [];
      if (st.out) problems.push('the working tree has uncommitted changes');
      if (!merged.ok) problems.push(`origin/cloud-session is not merged into ${br.out} (docs/OPERATIONS-CLOUD.md "Back on the workstation" step 1)`);
      return { ok: problems.length === 0, detail: problems.join('; ') || `${br.out}, cloud work merged` };
    } },
  { id: 'env', name: '.env and .env.local present (secrets stay on the workstation)', cmd: 'test -f .env && test -f .env.local',
    go: async () => { const miss = ['.env', '.env.local'].filter((f) => !fs.existsSync(path.join(ROOT, f))); return { ok: !miss.length, detail: miss.length ? `missing ${miss.join(', ')}` : 'present' }; } },
  { id: 'docker', name: `Docker running with ≥ ${NEEDS.dockerMemGiB} GiB for the WSL VM`, cmd: 'docker info --format "{{json .}}"',
    go: async () => {
      const r = run('docker', ['info', '--format', '{{json .}}']);
      if (!r.ok) return { ok: false, detail: `Docker is not answering (${r.err.split('\n')[0]}): start Docker Desktop` };
      const j = judgeDocker(parseDockerInfo(r.out));
      const wsl = WIN ? path.join(os.homedir(), '.wslconfig') : undefined;
      const cfg = wsl && fs.existsSync(wsl) ? parseWslConfig(fs.readFileSync(wsl, 'utf8')) : undefined;
      return { ok: j.ok, detail: [j.detail, ...j.problems, cfg ? `.wslconfig memory=${cfg.memory ?? '?'} swap=${cfg.swap ?? '?'}` : ''].filter(Boolean).join('; '), warn: j.warn };
    } },
  { id: 'gpu', name: 'RTX 5090 visible on the host and inside a container', cmd: `nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader,nounits; docker compose -p ${PROJECT} run --rm --no-deps --entrypoint nvidia-smi comfyui -L`,
    go: async () => {
      const r = run('nvidia-smi', ['--query-gpu=name,memory.total,driver_version', '--format=csv,noheader,nounits']);
      if (!r.ok) return { ok: false, detail: `nvidia-smi failed (${r.err.split('\n')[0]})` };
      const host = judgeGpu(parseNvidiaSmi(r.out));
      if (!host.ok) return { ok: false, detail: host.problems.join('; ') };
      const c = run('docker', compose('run', '--rm', '--no-deps', '--entrypoint', 'nvidia-smi', 'comfyui', '-L'), { timeoutMs: 5 * 60_000 });
      return { ok: c.ok && /RTX 5090/i.test(c.out), detail: c.ok ? `${host.detail}; in a container: ${c.out.split('\n')[0]}` : `the GPU is not visible inside containers (${c.err.split('\n')[0]}): check the NVIDIA runtime in Docker Desktop` };
    } },
  { id: 'db', name: 'Database up, backed up before any migration', cmd: `docker compose -p ${PROJECT} up -d db; docker exec ${PROJECT}-db-1 pg_dump -U vewbox -Fc vewbox -f /tmp/resume.dump; docker cp …`,
    go: async () => {
      const up = run('docker', compose('up', '-d', 'db')); if (!up.ok) return { ok: false, detail: up.err };
      const h = await waitHealthy('db', 30); if (!h.ok) return h;
      const stamp = new Date().toISOString().replace(/[:.]/g, '').slice(0, 15);
      const dir = path.join(ROOT, 'var', 'backups', 'resume'); fs.mkdirSync(dir, { recursive: true });
      const d = run('docker', ['exec', `${PROJECT}-db-1`, 'pg_dump', '-U', 'vewbox', '-Fc', 'vewbox', '-f', `/tmp/resume-${stamp}.dump`]);
      if (!d.ok) return { ok: false, detail: `pg_dump failed: ${d.err}` };
      const cp = run('docker', ['cp', `${PROJECT}-db-1:/tmp/resume-${stamp}.dump`, path.join(dir, `vewbox-${stamp}.dump`)]);
      return { ok: cp.ok, detail: cp.ok ? `backup var/backups/resume/vewbox-${stamp}.dump` : cp.err };
    } },
  { id: 'migrate', name: 'Migrations applied (0027 production context and anything newer)', cmd: 'pnpm db:migrate',
    go: async () => { const r = run('pnpm', ['exec', 'tsx', '--env-file=.env', '--env-file-if-exists=.env.local', 'src/server/db/cli.ts', 'migrate']); return { ok: r.ok, detail: r.ok ? (r.out.split('\n').pop() ?? 'migrated') : r.err.split('\n').slice(-3).join(' ') }; } },
  { id: 'models', name: 'Model files verified on the volume (the gates’ groups)', cmd: `docker run --rm -v ${PROJECT}_models:/models alpine cat /models/.manifest-state.json  (+ every file's size, against docker/models/manifest.json)`,
    go: async () => {
      const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'docker', 'models', 'manifest.json'), 'utf8'));
      const st = run('docker', ['run', '--rm', '-v', `${PROJECT}_models:/models`, 'alpine', 'cat', '/models/.manifest-state.json']);
      const sz = run('docker', ['run', '--rm', '-v', `${PROJECT}_models:/models`, 'alpine', 'sh', '-c', 'cd /models && find . -type f ! -path "*/.hf/*" -exec stat -c "%s %n" {} + | sed "s# \\./# #"'], { timeoutMs: 5 * 60_000 });
      if (!st.ok) return { ok: false, detail: `no fetcher state on the models volume (${st.err.split('\n')[0]}): docker compose -p ${PROJECT} --profile models run --rm models` };
      const v = verifyModels(manifest, JSON.parse(st.out), sz.out);
      return { ok: v.ok, detail: v.ok ? `${v.ready} files verified (${NEEDS.modelGroups.join(', ')})` : `missing: ${v.missing.slice(0, 8).map((m) => `${m.file} (${m.why})`).join('; ')}${v.missing.length > 8 ? ` … ${v.missing.length} in all` : ''}${v.unknownGroups.length ? `; unknown groups ${v.unknownGroups.join(', ')}` : ''} — docker compose -p ${PROJECT} --profile models run --rm models` };
    } },
  { id: 'comfyui', name: 'ComfyUI up; every node class and model file the workflows name is present', cmd: `docker compose -p ${PROJECT} up -d comfyui && node scripts/check-comfy-nodes.mjs`,
    go: async () => {
      const up = run('docker', compose('up', '-d', 'comfyui')); if (!up.ok) return { ok: false, detail: up.err };
      const h = await waitHealthy('comfyui', 60); if (!h.ok) return h;
      const stats = await http(`${COMFY}/system_stats`);
      const c = run('node', ['scripts/check-comfy-nodes.mjs']);
      return { ok: c.ok, detail: `${stats.ok ? (JSON.parse(stats.body).devices?.[0]?.name ?? 'device ?') : 'system_stats unavailable'}; ${c.ok ? 'nodes and models complete' : c.out.split('\n').slice(-6).join(' ')}` };
    } },
  { id: 'voices', name: 'Voice and transcription services up (not the LLM beside H3: host RAM)', cmd: `docker compose -p ${PROJECT} up -d tts tts-habibi tts-design asr`,
    go: async () => {
      const up = run('docker', compose('up', '-d', 'tts', 'tts-habibi', 'tts-design', 'asr')); if (!up.ok) return { ok: false, detail: up.err };
      const out = [];
      for (const s of ['asr', 'tts', 'tts-habibi', 'tts-design']) { const h = await waitHealthy(s, 90); out.push(h.detail); if (!h.ok) return { ok: false, detail: out.join('; ') }; }
      const asr = await http('http://127.0.0.1:8030/health');
      let caps = '';
      try { const j = JSON.parse(asr.body); caps = j.capabilities ? `; asr capabilities: ${Object.entries(j.capabilities).map(([k, v]) => `${k}=${v?.available ?? v}`).join(', ')}` : ''; } catch { /* older service */ }
      return { ok: true, detail: out.join('; ') + caps };
    } },
  { id: 'app', name: 'The studio answers (web /api/health, the worker)', cmd: START_APP ? 'pnpm dev (detached) + pnpm worker (detached), then GET /api/health' : 'GET /api/health (start `pnpm dev` and `pnpm worker` yourself, or pass --start-app)',
    go: async () => {
      if (START_APP) {
        const logs = path.join(ROOT, 'var', 'logs'); fs.mkdirSync(logs, { recursive: true });
        for (const [name, script] of [['web', 'dev'], ['worker', 'worker']]) {
          const out = fs.openSync(path.join(logs, `${name}-resume.log`), 'a');
          spawn(WIN ? 'pnpm.cmd' : 'pnpm', [script], { cwd: ROOT, detached: true, stdio: ['ignore', out, out], shell: WIN }).unref();
        }
      }
      for (let i = 0; i < 30; i++) { const h = await http(`${STUDIO}/api/health`); if (h.ok) { const j = JSON.parse(h.body); return { ok: true, detail: `version ${j.version}, intake ${j.intake?.paused ? `paused (${j.intake.reason ?? ''})` : 'open'}, queue ${JSON.stringify(j.queue)}` }; } await sleep(5000); }
      return { ok: false, detail: `${STUDIO}/api/health does not answer` };
    } },
  { id: 'acceptance', name: 'The acceptance checkpoint read; what stays valid; the gates', cmd: 'read docs/evidence/acceptance-v1/resume.json; git diff --name-only <checkpoint>..HEAD',
    go: async () => {
      const resume = JSON.parse(fs.readFileSync(path.join(ROOT, 'docs', 'evidence', 'acceptance-v1', 'resume.json'), 'utf8'));
      const base = run('git', ['rev-parse', '--verify', 'pre-cloud-acceptance-2026-10-05']).ok ? 'pre-cloud-acceptance-2026-10-05' : 'HEAD~1';
      const changed = run('git', ['diff', '--name-only', `${base}..HEAD`]).out.split('\n').filter(Boolean);
      const plan = resumePlan(resume, changed);
      const open = plan.gates.filter((g) => g.open || g.stale).map((g) => `${g.name}: ${g.stale ?? g.verdict}`);
      if (RESUME_INTAKE) { const r = run('pnpm', ['exec', 'tsx', '--env-file=.env', '--env-file-if-exists=.env.local', 'scripts/studio-intake.ts', 'resume']); if (!r.ok) return { ok: false, detail: `intake could not be resumed: ${r.err}` }; }
      return { ok: true, detail: `production ${plan.production?.id} “${plan.production?.title}”; new takes use the new code: ${plan.newTakesUseNewCode}; re-assemble: ${plan.reassemble}; open gate items: ${open.join(' | ') || 'none'}; intake ${RESUME_INTAKE ? 'RESUMED' : 'still paused (pass --resume-intake)'}`, plan };
    } },
];

const report = { at: new Date().toISOString(), mode: GO ? 'go' : 'plan', host: os.hostname(), platform: process.platform, steps: [] };
let started = !FROM;
console.log(`Vewbox local resume — ${GO ? 'RUN' : 'PLAN (nothing is changed; pass --go to run)'}\n`);
for (const s of STEPS) {
  if (!started && s.id === FROM) started = true;
  if (!started) { report.steps.push({ id: s.id, skipped: true }); continue; }
  if (!GO) { console.log(`  [${s.id}] ${s.name}\n        ${s.cmd}`); continue; }
  process.stdout.write(`  [${s.id}] ${s.name} … `);
  let r;
  try { r = await s.go(); } catch (e) { r = { ok: false, detail: String(e?.message ?? e) }; }
  report.steps.push({ id: s.id, name: s.name, ...r });
  console.log(`${r.ok ? 'OK' : 'STOP'}\n        ${r.detail}${r.warn ? `\n        warning: ${r.warn}` : ''}`);
  if (!r.ok) { console.log(`\nStopped at "${s.id}". Fix it, then: node scripts/resume-local.mjs --go --from ${s.id}`); break; }
}
console.log('\nThe real-generation gates (directive §16), in order — never past a failed gate without its root cause:');
for (const g of GATES) console.log(`  ${String(g.id).padStart(2)}. ${g.name} — ${g.proves}`);
if (GO) {
  const dir = path.join(ROOT, 'var', 'resume'); fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, `resume-${report.at.replace(/[:.]/g, '-')}.json`);
  fs.writeFileSync(file, JSON.stringify(report, null, 2));
  console.log(`\nReport: ${path.relative(ROOT, file)}`);
  process.exitCode = report.steps.every((x) => x.skipped || x.ok) ? 0 : 1;
}
